### PR TITLE
Update nl.coffee

### PR DESCRIPTION
**Pull request by Justinschut**

### CODE REVIEW

**Comment by Justinschut** [comment]
Not sure why this failed, I translated everything

**Comment by Bryukh** [comment]
@nwinter It's the second time when the coverage is reduced by 20% just for a translation. What can it be?

**Comment by sderickson** [comment]
Unknown; if you look at our coverage page it drops occasionally on single commits. This can definitely be ignored for client-only changes since our coverage is only currently applied to the server. Sorry for the confusion!

**Comment by Bryukh** [comment]
@sderickson so can we merge it or recommit it? It's the second time, the last time the contributor made the same commit with several parts and it was ok.

**Comment by sderickson** [comment]
Go ahead and merge. The real danger is if the tests fail; those should get re-run if it could be a false positive.

**Comment by Bryukh** [comment]
@Justinschut After conflict resolving it became ok. Thanks! Merged.

**Pull request merged**
