### PR TITLE
Enable C++

### PR DESCRIPTION
**Pull request by codeluggage**
# Context

We want to enable C++ :tada:

There are a few other mentions of cpp around the codebase. I looked into those too, but this alone looks like it does the trick 👍 

# How has this been tested? 

- Tested with personal account
- Tested with new classroom
- Tested with playing as a student in a classroom
- Local tests

### CODE REVIEW

**Comment by smallst** [comment]
LGTM.
 as for nick's suggestions, i think `enableCPP` in `User.coffee` need handle home users situation , so only `true` may be a problem. or you can add a new key for home users.
don't forget limit the levels like classroom version's ` if view.enableCpp && (course.id === view.utils.courseIDs.INTRODUCTION_TO_COMPUTER_SCIENCE || course.id === view.utils.courseIDs.COMPUTER_SCIENCE_2 || course.id === view.utils.courseIDs.COMPUTER_SCIENCE_3)`
the key limitation for enabling cpp in a level is array and json, if the level not contains them , enable cpp is just okay.

**Comment by smallst** [comment]
oh, another suggestion. merge this pr after https://github.com/codecombat/codecombat/pull/5925 merged.

**Comment by codeluggage** [comment]
Thank you for the feedback! I had initially made these changes too, and ran into some errors with `_this.spell is undefined` in `updateAether` - will loop back around on these issues with your comments.

**Comment by AndrewJakubowicz** [comment]
Hopefully those `spell` errors are addressed with the merged simulate cpp ladder PR.

**Comment by codeluggage** [comment]
No more errors after merging in master @AndrewJakubowicz  - good tip, thank you!

**Comment by nwinter** [comment]
Is this ready to go up?

**Pull request merged**
