### PR TITLE
Setup guide for headless_client.coffee

### PR DESCRIPTION
**Pull request by popey456963**

### CODE REVIEW

**Comment by popey456963** [comment]
You should not merge this commit just yet, I didn't realise committing would update this pull request.  Connecting over HTTPS is currently being tested.

**Comment by nwinter** [comment]
Connect to https://codecombat.com instead of https://direct.codecombat.com? We want caching, if it works, to reduce bandwidth; and we don't want to set up a cert for direct.

**Comment by popey456963** [comment]
Okay, I'll change that now.

**Comment by popey456963** [comment]
Reverted HTTPS, please accept documentation changes.

**Pull request merged**
