### PR TITLE
Update web_dev section in uk.cofee

### PR DESCRIPTION
**Pull request by Darejian**
Proposed translation of the web_dev section. "картинки" has been chosen intentionally as less formal than "зображення" and thus more children-friendly.

### CODE REVIEW

**Comment by Darejian** [comment]
Are there any actions required from me to address that (coverage remained 55.81%)?

**Comment by Imperadeiro98** [comment]
Hello, @Darejian! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that we can merge your pull request?

Regarding the coverage, you don't need to make any change, because it is not relevant to the changes you made.

**Comment by Darejian** [comment]
Hello, @Imperadeiro98! Thanks a lot for the explanations and the link. CLA is signed.

**Comment by Imperadeiro98** [comment]
👍

**Pull request merged**
