### PR TITLE
ENG-1212 - Add AI safety violations to teacher dashboard

### PR DESCRIPTION
**Pull request by adamkecskes**
backend PR: https://github.com/codecombat/codecombat-server/pull/1113
| before | after | 
| --- | --- |
| CodeCombat_-_Coding_games_to_learn_Python_and_JavaScript___CodeCombat | CodeCombat_Teacher_Dashboard |

update: original message added:
CodeCombat_Teacher_Dashboard

## Release Notes

- **New Features**
	- Enhanced English localization with detailed descriptions for Ozaria and CodeCombat programs, including new sections for educational resources and promotional content.
	- Added safety validation messages in AI project components to inform users of any concerns regarding unsafe messages.
	- Introduced conditional rendering for CodeCombat-specific progress indicators.

- **Bug Fixes**
	- Improved logic for handling unsafe messages in AI projects, ensuring accurate progress tracking.

- **Documentation**
	- Updated content to better reflect educational goals and offerings.

- **Style**
	- Enhanced visual formatting for safety validation messages across components.

### CODE REVIEW

**Review by smallst — CHANGES_REQUESTED** [review]
Logic LGTM but from your after image, the example is shown in green, while actually it shows  blue which is confusing. can we make better example either matching the color or use another color that shows with violations ?

image
image

**Comment by adamkecskes** [comment]
@smallst in the header the example is a `completed` level. on my dashboard example it is an `in-progress` one. Both the completed and inprogress projects could contain violations.

**Comment by mrfinch** [comment]
> @smallst in the header the example is a `completed` level. on my dashboard example it is an `in-progress` one. Both the completed and inprogress projects could contain violations.

yup, let's keep it like that for now. If it confuses lot of users, we can try to improve the identifier

**Review by mrfinch — COMMENTED** [review]
can we add the message content that is causing the violation if it's not too big of an effort? We can cap the message content of the message to 100 chars

**Review by mrfinch — APPROVED** [review]

**Pull request merged**
