### PR TITLE
Organize vagrant scripts

### PR DESCRIPTION
**Pull request by duybkict**
- Remove redundant vagrant scripts
- On host machine, now you can run: 
  + `scripts\vagrant\npm.sh [arguments]` which is equivalent to running `vagrant ssh` and `cd \vagrant` and `npm [arguments]` on guest machine
  + `scripts\vagrant\brunch.sh [arguments]` which is equivalent to running `vagrant ssh` and `cd \vagrant` and `brunch [arguments]` on guest machine
  + `scripts\vagrant\sync-mongo.sh` to update database
  + `scripts\vagrant\backup-mongo.sh` to backup database

### CODE REVIEW

**Comment by sderickson** [comment]
I'm not sure how, but it looks like those old, squashed commits are still coming along for the ride. I checked your [master branch](https://github.com/duybkict/codecombat/commits/master?author=duybkict) and commits like [`remove nvm`](15a1bcde25dd2a1229066b9ed7ae17321ec6df28) aren't present. Perhaps you branched off `vagrant-box` instead of `master`?

We're in hairy git territory, so if you want I can either rebase the relevant commits onto our master, or you can keep messing around with git until a pull request just shows the intended commits.

**Comment by duybkict** [comment]
please check again if it's OK this time

**Comment by sderickson** [comment]
Now there are more :( See above. The PR should only have those commits which are relevant, which I think are "organize vagrant scripts", "fix bug with passing arguments", and "add scripts for brunch".

**Comment by duybkict** [comment]
see #3652, I will close this pull request

**Pull request closed without merging**
