### PR TITLE
Update ja.coffee

### PR DESCRIPTION
**Pull request by Coderaulic**
Updated translation in:
nav:
play:
login:
signup:
recover:
items:
units: Note that in Japanese, measurements of time don't have individual or singular form: As in "a year" and "years" is still the same.
play_level:

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hi, @Coderaulic! Thanks for your translations.

**Comment by Coderaulic** [comment]
How soon does the changes take effect?

**Comment by Imperadeiro98** [comment]
It depends on when the changes are sent to production.

**Comment by Coderaulic** [comment]
I see, so is it one a day, once every 6hours/ 12 hours that sort of thing till the new changes get pushed in?

**Comment by Imperadeiro98** [comment]
Don´t really know. Sometimes minutes, other times hours. Just be patient! It will eventually happen.

**Comment by Coderaulic** [comment]
If I can see and confirm the changes in the game sooner, I will be able to make better translations or see if I did anything wrong. Hehe I will be patient :+1:

**Comment by Coderaulic** [comment]
How do I get added to diplomat list?

**Comment by Imperadeiro98** [comment]
Hi, @Coderaulic! I added you in [this](https://github.com/codecombat/codecombat/commit/3068f18443fd7115259f7d67bc92c7cc8c24cdb8) commit!

**Comment by Coderaulic** [comment]
Thanks!

**Pull request merged**
