### PR TITLE
Upgrade SpellPaletteView, make PlayLevelView resizing smarter, and fix many visual issues while playing levels

### PR DESCRIPTION
**Pull request by nwinter**
Bring back the old below-editor code documentation area when there aren't many APIs, modernizing it in the process. This gives us more space for the Surface game area. When in this mode, method docs do update with their interpolated property values, since they are generated just-in-time. Defaults to bottom positioning when there are fewer than 16 APIs, or you can use ?apis=bot or ?apis=mid to force the alternative layout.

Fix up a lot of dynamic sizing code and styling to make better use of the available screen space, including letting code editor flex to as small as is needed for 80 characters or as wide as half the screen to help either give the Surface more space or to keep it from overflowing the bottom of the window.

Remove various dead code areas and fix up minor layout issues within PlayLevelView for CodeCombat. Post-comment insertion point yellow gutter arrows are back and visible, the Classrom JS|PY button is gone, GameDevTrackView isn't erroneously pulling in Ozaria styling, error message positioning is better, the LevelDialogueView now overlays the
playback bar and HUD rather than the Surface, the goals area doesn't get so big so eagerly, and many elements are now positioned more reliably near the edes of the Surface or code area.

Merges a few more .coco and .ozar files, so now we can do things in CodeCombat like edit label formatting inside levels or show paths for multiple Thangs like in Ozaria.

Assorted screenshots of the changes (new on top or left because why make it intuitive?):

## Default first-level experience, 500% as much of the level is visible
Screen Shot 2022-09-30 at 16 25 38

---------------------

## Footer adjusts so tall screens don't look busted
Screen Shot 2022-09-30 at 16 26 11

---------------------

## Long code still adjusts editor length properly
Screen Shot 2022-09-30 at 16 26 59

---------------------

## Large screens shrink editor to 80 char columns for more game space
Screen Shot 2022-09-30 at 16 28 09

### (previously, it was always 43.5% of the screen width)
Screen Shot 2022-09-30 at 16 28 12

---------------------

## When multiple API sections are needed, three-column layout still activates
Screen Shot 2022-09-30 at 16 28 59
Screen Shot 2022-09-30 at 16 29 01

---------------------

## APIs are still grouped by the item that grants them, when relevant
Screen Shot 2022-09-30 at 16 31 38

---------------------

## API docs are available on hover, or clikck to pin, instead of sliding out
Screen Shot 2022-09-30 at 16 32 02

---------------------

## Fixed GameDevTrackView style bleed over from Ozaria
Screen Shot 2022-09-30 at 16 35 13

### CODE REVIEW

**Comment by Bryukh** [comment]
YES!

**Comment by Zerrien** [comment]
WOOOAHHH

**Comment by smallst** [comment]
Too long to manually check every file. so i try local server to use it. 
in every aspect radio it works good to me. 
just one thing. seems new (actually old?) UI for docs below the editor, it supports `hover to temp display docs` and `click to hold it`. there're 2 issues i think: 1. for large screen, hover & click generate different style which seems not good. 
image
image
2. in old middle-doc view, hover doesn't do anything. and click still give old style. is it in purpose? i would like make hover&click events to do same thing in different levels. 
image
image

**Comment by nwinter** [comment]
The old middle API column view doesn't really have the screen space for hover popover docs on small screens, so I left that the way it was–it might be a good thing to do on larger screens, though. I'll save it as future work, alongside tweaking the hover positioning on large screens for pinned docs.

**Pull request merged**
