### PR TITLE
Update ja.coffee

### PR DESCRIPTION
**Pull request by sacun**
Unification of punctuation, correction and addition

### CODE REVIEW

**Comment by Bryukh** [comment]
@sacun Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Chaboi45** [comment]
> コーディングゲーム is a bit misleading, you create your own **game**, not a coding platform. I believe you should change コーディングゲーム to ゲーム

```
meta_description: "プログラミングゲームを通してコードを学ぼう。Python、JavaScript、HTMLをパズルを解くように学んで、あなた自身のコーディングゲームやウェブサイト作りを学びましょう。"
```
to
```
meta_description: "プログラミングゲームを通してコードを学ぼう。Python、JavaScript、HTMLをパズルを解くように学んで、あなた自身のゲームやウェブサイト作りを学びましょう。"
```

**Comment by sacun** [comment]
@Bryukh I'm sorry I'm late, I signed!

@Chaboi45 Thank you very much. indeed. I changed it!

**Comment by Bryukh** [comment]
Thanks!

**Pull request merged**
