### PR TITLE
Fix pt-BR translation individuals_or_parents 

### PR DESCRIPTION
**Pull request by zolfer**
From: individuals_or_parents: "Individuais e Resposáveis"
To: individuals_or_parents: "Individuais e Responsáveis"

### CODE REVIEW

**Comment by Bryukh** [comment]
@zolfer Hi, could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by zolfer** [comment]
I could accept, but when I try to login, it shows me an error.
image

When I try to create a new account, the validator stops me.
image

I tried to recover the password, but it does not seem to work that way.

**Comment by shubhi1092** [comment]
@zolfer Can you try again, I have added the domain to the authorized list.

**Comment by zolfer** [comment]
Done. =)
image

**Comment by Bryukh** [comment]
Thanks!

**Pull request merged**
