### PR TITLE
run code first then save chat message

### PR DESCRIPTION
**Pull request by smallst**

### CODE REVIEW

**Review by nwinter — CHANGES_REQUESTED** [review]
When the user chats, we don't want to run the code if it has already been run, only if the code is different from what was last run. (Ideally we would also wait for the run to complete and get the new goal and error states, but we might have to update the chat UI for that to indicate that we were waiting for it...?)

**Comment by smallst** [comment]
@nwinter i think `onCastButton` message in spellview would check if the code is different from what was last run.

**Comment by nwinter** [comment]
@smallst just tried it, it does recompile the code. In addition to SpellView, there are a bunch of other places that subscribe to `tome:manual-cast` events. So, we shouldn't fire that event unless we actually need to rerun the code.

**Comment by smallst** [comment]
@nwinter updated, can review again

**Review by mrfinch — APPROVED** [review]
looks good, can you remove console.log?

**Pull request merged**
