### PR TITLE
Update zh-HANT.coffee

### PR DESCRIPTION
**Pull request by leorlf2h**
2016/MAY/15th leorlf2h  XarBuXar(ingameID)

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @leorlf2h! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by leorlf2h** [comment]
OK,it done. :)

**Comment by Imperadeiro98** [comment]
Great :+1:

**Comment by leorlf2h** [comment]
Could you tell me how long it will take to get online?
I can't wait to introduce this game to my friend . XD

**Comment by Imperadeiro98** [comment]
I can tell you for sure, because it depends on when a new production deploy happens, and there is not a fix schedule.
I'm glad you like the game and hope your friends like it too!

**Pull request merged**
