### PR TITLE
fix malformed comment in main.html

### PR DESCRIPTION
**Pull request by rgardler**

### CODE REVIEW

**Comment by nwinter** [comment]
I had to stare at this one for a while. I think the comment is formatted correctly, such that IE will understand it as a comment, but that other browsers won't (and so they will include it). I tested your changes, anyway, and nothing loads on the site. So my guess is that it's working as intended, although we don't need that other cosmetic nested comment, so I'll remove that.

Feel free to reopen if I'm missing something.

**Comment by rgardler** [comment]
Actually I'm running in IE. It creates a warning (not an error so not the end of the world). Not sure why you are seeing nothing with this change, perhaps an incompatibility with whatever browser you are using.

Anyway, comments in HTML are not '<!' but '' not '>') - as per all other comments in this same file.

**Comment by nwinter** [comment]
@differentmatt can you look at this?

**Comment by differentmatt** [comment]
These are conditional comments read by Internet Explorer.  The ones you're suggesting we change need to remain downlevel-revealed.  These weird comments are specifically addressing IE9 issues, which are noted above each conditional comment block.

More info: https://msdn.microsoft.com/en-us/library/ms537512(v=VS.85).aspx#dlrevealed

Your changes will specifically comment out required script file includes on non-IE browsers, which is why Nick didn't see anything load with your changes.

Feel free to file an issue or submit a pull request for any warnings you're seeing in IE.  Thanks!

**Pull request closed without merging**
