### PR TITLE
app/locale: translation for ZH_HANT and ZH_HANS

### PR DESCRIPTION
**Pull request by zxcpoiu**
app/locale: translation for ZH_HANT and ZH_HANS

### CODE REVIEW

**Comment by zxcpoiu** [comment]
Did I do anything wrong?

**Comment by nwinter** [comment]
Nope, your pull request is great–thanks for adding those translations! Can I get you to [sign the CLA](http://codecombat.com/cla) so I can merge this in?

**Comment by zxcpoiu** [comment]
Yes, of course. finished.

**Comment by nwinter** [comment]
Thanks!

**Pull request merged**
