### PR TITLE
Fix bug: cannot upload profile picture

### PR DESCRIPTION
**Pull request by h3yduck**
In the code before, onInputChanged function was called manually, but the parameter was not passed. I think it's better to trigger the event, than calling the callback function of the event.

### CODE REVIEW

**Comment by nwinter** [comment]
Thanks @h3yduck! Have you tested to see if this fixes the upload bug? I haven't drilled too deeply, but I didn't see what effect the `changed` class actually has on anything.

**Comment by h3yduck** [comment]
No problem! Yeah i forgot: the upload works now! I think the changed class doesn't do anything, but i'm not too familiar with the codebase yet, so i left it in there.

**Comment by namchester** [comment]
It still shows an error.

**Comment by h3yduck** [comment]
image

I don't know why, there is no error message for me.

**Comment by namchester** [comment]
Not working for me. 
screenshot from 2015-02-07 18 08 42

**Comment by nwinter** [comment]
Have you [synced your fork](https://help.github.com/articles/syncing-a-fork/) to get the latest master?

**Comment by namchester** [comment]
Was working on Chrome, but not on Firefox. Strange! Anyhow, it is working perfectly. Sorry to waste your time!

**Pull request merged**
