### PR TITLE
Update nl-NL.coffee

### PR DESCRIPTION
**Pull request by SebastiaanBekker**

### CODE REVIEW

**Comment by SebastiaanBekker** [comment]
@Bryukh Question on one of the lines:
# victory_experience_gained: "XP # Keywords--these translations show up on hover, so please translate them all, even if it's kind of long. (In the code editor, they will still be in English.)"
 
Is the quotiation right? Or should it be after XP? and the rest then as a comment?

**Comment by Bryukh** [comment]
@SebastiaanBekker I think it should be after XP

**Comment by Bryukh** [comment]
@SebastiaanBekker in en.coffee this is `victory_experience_gained: "XP Gained"`

**Comment by Bryukh** [comment]
Merged.

**Pull request merged**
