### PR TITLE
Fix some translations for de de

### PR DESCRIPTION
**Pull request by s-gerber**
This PR should fix a _few_ spelling errors and inconsistencies. It seems that some sentences are formal and some are informal. This one was even both:

```
Schreibe hier ihre Emailadresse rein und wir werden es ihnen zeigen.
```

`Schreibe` is informal and `ihre / ihnen` is formal. Sounds pretty weird. There are most probably a few other cases where this happened.

Is the double whitespace in the end intended in

[`youve_been_invited_1: "Du wurdest eingeladen,  "`](https://github.com/codecombat/codecombat/blob/master/app/locale/de-DE.coffee#L1395)?

There is sometimes [a double whitespace between sentences](https://github.com/codecombat/codecombat/blob/master/app/locale/de-DE.coffee#L1408). Is this because of technical / formatting reasons (because you usually wouldn't usually make a double whitespace here).

PS: [Travis currently has an capaticity issue](https://www.traviscistatus.com/incidents/4vdl52d28hz3)

### CODE REVIEW

**Comment by Bryukh** [comment]
@s-gerber  Thanks. Could you sign our [CLA](http://codecombat.com/cla) so we can accept your PR?

**Comment by s-gerber** [comment]
@Bryukh so it needs a CodeCombat account to sign this, right? How are GitHub and the CodeCombat accounts connected?

**Comment by Bryukh** [comment]
Yes, you need a CodeCombat account. It legal issues, I don't know details about it.

**Comment by s-gerber** [comment]
I agreed 👍

**Comment by Bryukh** [comment]
Thanks! merged.

**Pull request merged**
