### PR TITLE
Update ellipse.coffee

### PR DESCRIPTION
**Pull request by coder0xff**
An improved (and untested) implementation for containsPoint

### CODE REVIEW

**Comment by nwinter** [comment]
@coder0xff it looks like some of the assertions in these two test cases failed: https://github.com/codecombat/codecombat/blob/master/test/app/lib/world/ellipse.spec.coffee#L10-L35

This is the Travis CI output: https://travis-ci.org/codecombat/codecombat/builds/51791907#L1996-L2028

We can probably get your dev server working so you can run the tests and maybe we can figure out what's going wrong with the new containsPoint.

**Comment by nwinter** [comment]
@coder0xff Did you want to check out those tests on containsPoint?

**Comment by coder0xff** [comment]
Sorry, I haven't had the time. I'll try to get to it this weekend.

**Comment by coder0xff** [comment]
Hey Nick. I got the dev environment working and did the unit tests. I've
committed the fix to the same branch. Do I need to send another pull
request? I'm still new to that whole workflow.

**Comment by Imperadeiro98** [comment]
If you commit to the same branch, the change will appear in this one (as indeed happened).

**Comment by nwinter** [comment]
Awesome, thanks @coder0xff!

**Pull request merged**
