### PR TITLE
Email validation

### PR DESCRIPTION
**Pull request by JordanLittell**
-only client-side validation

### CODE REVIEW

**Comment by nwinter** [comment]
First commit is for https://github.com/codecombat/codecombat/issues/2785, right? And second for https://github.com/codecombat/codecombat/issues/914.

@sderickson want to review?

**Comment by JordanLittell** [comment]
First commit is for #2785 second commit is to validate emails entered in textarea.recipient-emails in subscriptionView, don't believe there exists an issue.

**Comment by sderickson** [comment]
@JordanLittell the first commit adds a month, however that just makes the date always today + one month. Fixed this with 844bc94.

The second one is mostly there. Just two requests:
* Make the regex looser and simpler. Perhaps the [second one here](http://www.webmonkey.com/2008/08/four_regular_expressions_to_check_email_addresses/). The link also has the reasoning.
* Don't let the textarea get cleared of emails when they don't pass the regex. The user shouldn't have retype/repaste the emails, just edit whichever ones are invalid.

Thanks!

**Comment by JordanLittell** [comment]
@sderickson thanks for letting me know. I'll merge, make the changes for the validation, and then push again.

**Pull request closed without merging**
