### PR TITLE
Update fr.coffee Translate text

### PR DESCRIPTION
**Pull request by EloCodes**
here you will find some translation for the game platform CodeCombat

### CODE REVIEW

**Comment by Bryukh** [comment]
@EloCodes Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by EloCodes** [comment]
@bryukh it's done

**Comment by Bryukh** [comment]
@EloCodes Could you remove config and not related files from your PR?

**Comment by EloCodes** [comment]
@Bryukh How can I do this ? 
I need some information to remove other files

**Comment by Bryukh** [comment]
I think the simplest way it would be to close this PR. Copy your fr.locale and create a new PR with this file changed only.

**Pull request closed without merging**
