### PR TITLE
Update fr.coffee v1.1

### PR DESCRIPTION
**Pull request by AminSai**

### CODE REVIEW

**Comment by AminSai** [comment]
ping @Bryukh

**Comment by Bryukh** [comment]
@AminSai could you sign our [CLA](http://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by AminSai** [comment]
> @AminSai could you sign our [CLA](http://contributors.codecombat.com/cla) so we can accept your PR?

Done

**Comment by Bryukh** [comment]
Thanks! Merged.
Sorry for the delay.

**Pull request merged**
