### PR TITLE
Vagrant box

### PR DESCRIPTION
**Pull request by duybkict**
Update Vagrant setup scripts
install nodejs using nvm
fix issues with Windows/Linux new line characters
update auto-reload-brunch
drop bless-brunch
resolve related issue #3588

### CODE REVIEW

**Comment by sderickson** [comment]
Just ran `vagrant up`, and it didn't work on my machine (Mac). It ends with this:

```
==> default: Unpacking mongodb-org-mongos (2.6.12) ...
==> default: Selecting previously unselected package mongodb-org-tools.
==> default: Preparing to unpack .../mongodb-org-tools_2.6.12_amd64.deb ...
==> default: Unpacking mongodb-org-tools (2.6.12) ...
==> default: Selecting previously unselected package mongodb-org.
==> default: Preparing to unpack .../mongodb-org_2.6.12_amd64.deb ...
==> default: Unpacking mongodb-org (2.6.12) ...
==> default: Processing triggers for man-db (2.6.7.1-1) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: ureadahead will be reprofiled on next reboot
==> default: Setting up mongodb-org-shell (2.6.12) ...
==> default: Setting up mongodb-org-server (2.6.12) ...
==> default: Adding system user `mongodb' (UID 107) ...
==> default: Adding new user `mongodb' (UID 107) with group `nogroup' ...
==> default: Not creating home directory `/home/mongodb'.
==> default: Adding group `mongodb' (GID 113) ...
==> default: Done.
==> default: Adding user `mongodb' to group `mongodb' ...
==> default: Adding user mongodb to group mongodb
==> default: Done.
==> default: mongod start/running, process 8811
==> default: Setting up mongodb-org-mongos (2.6.12) ...
==> default: Setting up mongodb-org-tools (2.6.12) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Setting up mongodb-org (2.6.12) ...
==> default: start: Job is already running: mongod
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

It also takes a rather long time to set up Vagrant. In that I did `vagrant up`, got the error, did `vagrant destroy` and `vagrant up` again to verify and it seemed to download everything anew. This may be because the install process didn't finish? I'm not familiar with the system so I'm not sure what to expect. I've only worked with Docker before, though.

**Comment by duybkict** [comment]
the outputs seems totally OK, you could go `vagrant ssh`, `cd /vagrant` and run `npm run dev` to start your server, if you have any trouble just let me know and I will support
the process is rather long because I take an extra step to convert Windows newline characters into Linux newline characters with every files in folder `/app`

**Comment by sderickson** [comment]
Got it to work, after cloning the repo anew and running `npm install` before `npm run dev`. Squashed into one commit and merged in: 672c89e0bca913af06349c76bfbb9301edb9f3e3. Thanks!

**Comment by sderickson** [comment]
Could you update the [Vagrant Dev Setup Wiki Page](https://github.com/codecombat/codecombat/wiki/Dev-Setup%3A-Vagrant)? In particular, I don't think the specialized vagrant scripts need running.

**Comment by duybkict** [comment]
OK, I will update the WIki Page, and might also remove the vagrant scripts as they are actually redundant

**Comment by sderickson** [comment]
Thanks! 👍

**Pull request closed without merging**
