### PR TITLE
Add npm&bower update to SCOCODE.bat. Update ver #

### PR DESCRIPTION
**Pull request by nixel2007**
Recent update of aether forced me to run npm update & bower update (thanks Nick for tip).
So Nick and me decided to add this command to scocode and coco-dev-setup.

I think, we also need to add some comments to linux setup here https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Linux

### CODE REVIEW

**Comment by nixel2007** [comment]
Also we need to update link to archive here https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Windows

There is a new version of packed setup: https://drive.google.com/file/d/0BzrHpvxfLxBiNk9uX1VDSVJyUU0/view?usp=sharing (please reupload on some coco resource)

**Comment by nixel2007** [comment]
Hm... Looks like configuration.exe this script generated doen't work at all.
Also setup ver 3.7 and setup files at /scripts/windows/coco-dev-setup don't match.
I'll try to find problem.
No need to update link to archive at wiki, leave it as 3.7 for a while.

**Comment by nwinter** [comment]
Nice. Now I'm wondering if this will work well and we should have it be part of the Linux/Mac dev process, too...

**Comment by nixel2007** [comment]
You can update linux and macos pages to run 5 commands, not 3 :)
also it may be good idea to create some shell-script (bash as most common?) same to SCOCODE.bat

**Pull request merged**
