### PR TITLE
Update it.coffee

### PR DESCRIPTION
**Pull request by chardido**
i've traduced some stuffs

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @chardido! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by chardido** [comment]
Sure, but there's a problem. In the login form it says "Email not found". So i can't login

Date: Sun, 10 Apr 2016 07:37:12 -0700

**Comment by Imperadeiro98** [comment]
Have you created an account on the CodeCombat site?

**Comment by chardido** [comment]
yes i did, i've also played some games

Date: Tue, 12 Apr 2016 07:14:50 -0700

**Comment by Imperadeiro98** [comment]
Then, it should let you sign in and sign the CLA. Can you try one more time?

**Comment by Imperadeiro98** [comment]
Will reopen if CLA gets signed.

**Pull request closed without merging**
