### PR TITLE
chore (names.coffee): Add more Thang names for #53

### PR DESCRIPTION
**Pull request by gnerkus**

### CODE REVIEW

**Comment by nwinter** [comment]
Thanks @gnerkus!

**Comment by andela-ioraelosi** [comment]
You're welcome. 

I noticed my commit broke the build. I'm still investigation why. I apologize for not running the tests after I committed my changes.

I'll run the tests as soon as I can and fix any issues I encounter.

**Comment by gnerkus** [comment]
You're welcome @nwinter 

I noticed my commits broke the build. I'm still investigating why. I'll fix the issue once I discover it.

I'll make sure to run tests next time I make commits to the repo.

**Comment by nwinter** [comment]
I think the tests have been failing for another reason. I suppose I should have to check it out soon.

**Pull request merged**
