### PR TITLE
update fr.coffee

### PR DESCRIPTION
**Pull request by clescot**

### CODE REVIEW

**Comment by clescot** [comment]
Here are the Travis last errors : 
```
(current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.12.2/bin/node" "/home/travis/.nvm/versions/node/v6.12.2/bin/npm" "install"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! codecombat@1.0.0 postinstall: `bower install && webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the codecombat@1.0.0 postinstall script 'bower install && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/codecombat/codecombat/npm-debug.log
The command "eval npm install  " failed. Retrying, 2 of 3.
```

**Comment by Bryukh** [comment]
@clescot Could you sign our [CLA](contributors.codecombat.com/cla) so we can accept your PR?

**Comment by clescot** [comment]
@Bryukh ,
how can i sign your CLA ?
best regards,

**Comment by clescot** [comment]
i've signed (clicked with my github id) your cla at this address : 
https://codecombat.com/cla

**Comment by Bryukh** [comment]
Thanks. I've fixed errors. Please be careful with indents and quotes.

**Comment by clescot** [comment]
@Bryukh thanks for the fix!

**Pull request merged**
