### PR TITLE
Add and improve some translations (de_DE)

### PR DESCRIPTION
**Pull request by l34kr**
I improved translations regarding grammatics and spelling and added one new translation. 

I'm willing to put more effort and work in this if there isn't enough help already :)

### CODE REVIEW

**Comment by l34kr** [comment]
Can someone help? Why is my coverage decreased? Do I have an old version of the file or something? :/

I editted the file right in the CodeCombat repo which than (on save/commit) "became" a file on a new branch in my fork.

**Comment by joca16** [comment]
I think your workflow is correct and the diffs  -in my opinion - do not indicate that you had an old version or some text was lost
I am sure Brykh will give you a feedback if there should be any issues with your translation or he will fix minor mistakes if there should be any.
BTW, I like your improvements and I am sure your help here would be much appreciated!

**Comment by l34kr** [comment]
I checked it too and at least the number of lines (or sloc) is identical. The history of both files (in my fork and in the original repo here) seem to be identical too. 
I will wait for further feedback :)

**Comment by Bryukh** [comment]
@l34kr Thanks. Could you sign our [CLA](https://codecombat.com/cla) so we could accept your pull request?

**Comment by l34kr** [comment]
Done :)

**Comment by Bryukh** [comment]
Thanks. Merged.

**Pull request merged**
