### PR TITLE
First pull request as translator

### PR DESCRIPTION
**Pull request by Kavignon**
See commit messages.

### CODE REVIEW

**Comment by Kavignon** [comment]
I don't understand what's wrong with my commits. I don't get the error that is being shown by the CI

**Comment by Kavignon** [comment]
Now, I don't get why it worked. But I should be happy it did, right ?

**Comment by Kavignon** [comment]
Oh and I signed the CLA, so my pull request is good to be merged !

**Comment by Imperadeiro98** [comment]
Hello, @Kavignon! Thank you for contributing. Could you open a pull request with only the changes to the French file? Because you did some changes that you are also committing.

**Comment by Kavignon** [comment]
@Imperadeiro98 How can I do that ? How can I excluded elements that were already commited ?

**Comment by Imperadeiro98** [comment]
You can create a new branch from master and apply only the changes you want to it.

**Pull request closed without merging**
