### PR TITLE
Edited nb.coffee

### PR DESCRIPTION
**Pull request by matifol**

### CODE REVIEW

**Comment by mogsie** [comment]
Dratz. lots of double work here! https://github.com/codecombat/codecombat/pull/2261

**Comment by matifol** [comment]
Ops, sorry. Didn't see. Guess I took for granted I was the only one working on this.

**Comment by nwinter** [comment]
Got it all merged–sorry about that. Thank for such heroic double Norwegian translation! If you notice any strings that seem better translated in one version than the version that I merged in, please feel free to send another pull request with those updates.

**Comment by mogsie** [comment]
Didn't seem that there was too much overlap, in fact :)  Someone should remove the "no" language.  The languages here are "nb" and "nn". "no" is deprecated, I believe.

**Comment by nwinter** [comment]
Ah, perhaps! Can you tell me:

1. Which browser accept-languages will browsers send when set to various Norwegian language branches?
2. Which versions of Norwegian will which people use?

**Comment by matifol** [comment]
Good stuff!
Yea, "no" is probably no good. Like @mogsie says "nb" and "nn" are the ones being used. "nb" will be the most common one. "nn" is kind of a secondary written language.

**Comment by mogsie** [comment]
@nwinter:
nb = "Norwegian Bokmål", used in many populous parts of the country, including the capital.
nn = "Norwegian Nynorsk", used in many other populous and not so populous parts.

A windows (only Vista :( ) machine I have access to has "Norwegian Bokmål" locale, and sends these Accept-Language headers:

Chrome/Windows: nb-NO,nb,no,nn,en-US  (with decreasing qualities)
FF/Windows: nb-no,nb,no-no,no,nn-no,nn,en-us (also decreasing q values)
IE10/Windows: nb-NO

Pretty sure a machine with "Norwegian Nynorsk" would see "nn" somehow first in the list. :)

Now we need to find someone with the time to translate nn.coffee!

Historically there _was_ a no locale, but it was deprecated and removed by operating systems a long time ago.

**Comment by mogsie** [comment]
@matifol I'll do some post-merge cleanup. Some of  your edits were better than mine ;-)

**Comment by nwinter** [comment]
Okay, I just tested and when I set Chrome to nn, it doesn't even ask for no. So fallback between nb, nn, and no wouldn't work anyway. Let's remove no.coffee. Is there anything in there that should be migrated, or is it all redundant?

**Comment by mogsie** [comment]
I think it's al redundant. We have it if we need it :)

**Comment by matifol** [comment]
Thanks @mogsie, good stuff :-)

**Pull request merged**
