### PR TITLE
Fixed minor typo in Chinese

### PR DESCRIPTION
**Pull request by m4jing**

### CODE REVIEW

**Comment by nwinter** [comment]
Hi @m4jing, can you please [sign our CLA](https://codecombat.com/cla) so I can merge this in? Thanks!

**Comment by m4jing** [comment]
@nwinter Done with the signing, please check. Thanks.

**Comment by nwinter** [comment]
Hi @m4jing, I think it maybe signed on another server? I don't see it. Are you in China? Can you possibly sign again here at https://contributors.codecombat.com/cla?

Sorry for the hassle, and thanks for your patience!

**Comment by m4jing** [comment]
@nwinter Yes, I'm in China. I created another account. I think it will be OK now. 😄

**Comment by nwinter** [comment]
Thanks @m4jing!

**Comment by m4jing** [comment]
My pleasure.

**Pull request merged**
