### PR TITLE
Narrow section border in parent page

### PR DESCRIPTION
**Pull request by mohit-codecombat**
Lines on both sides of FAQs and Student Outcomes Headers should be narrower.
Live-coding-classes-from-CodeCombat-8
Live-coding-classes-from-CodeCombat-7
Live-coding-classes-from-CodeCombat-6
Live-coding-classes-from-CodeCombat-5

### CODE REVIEW

**Review by AndrewJakubowicz — COMMENTED** [review]
Great work and screenshots!!!

Can this be done without `!important`?

**Comment by mohit-codecombat** [comment]
Removed `!important` from css style

> Great work and screenshots!!!
> 
> Can this be done without `!important`?

**Comment by mohit-codecombat** [comment]
Removed !important from css style

**Comment by AndrewJakubowicz** [comment]
@mohit-codecombat  Did you mean to close the PR?

**Comment by mohit-codecombat** [comment]
> @mohit-codecombat Did you mean to close the PR?

No, Sorry It was by mistake. Reopened again.

**Review by AndrewJakubowicz — APPROVED** [review]
LGTM! Didn't manually test. Love the changes!

🚢

**Pull request merged**
