### PR TITLE
Update sk.coffee

### PR DESCRIPTION
**Pull request by cundamic**
teachers_quote

### CODE REVIEW

**Comment by Bryukh** [comment]
@cundamic Thanks. But why did you reverse some parts of the translations (Sk to En)?

**Comment by cundamic** [comment]
You can reverse them back.

Dňa 5.4.2017 7:56 používateľ "Bryukhanov Valentin" <notifications@github.com>
napísal:

**Comment by Bryukh** [comment]
Only be editing the file by hands :-(

**Comment by Bryukh** [comment]
@cundamic I can't reverse the part of the commit. Only by editing it

**Pull request closed without merging**
