### PR TITLE
Update nl.coffee

### PR DESCRIPTION
**Pull request by suzibol**

### CODE REVIEW

**Comment by suzibol** [comment]
What happened? Can someone help me fix it?

**Comment by portothree** [comment]
> What happened? Can someone help me fix it?

Your build has failed, check if the ".travis.yml" file on your repo are correct. You can also visit https://travis-ci.org, find the build process and try again

**Comment by suzibol** [comment]
> > What happened? Can someone help me fix it?
> 
> The attempt to build has failed, check if the ".travis.yml" file on your repo are correct. You can also visit https://travis-ci.org, find the build process and try again

I went to https://travis-ci.org but I'm not a programmer and I don't know what to do. I don't see any mistakes?

**Comment by Bryukh** [comment]
Hooray!

**Pull request merged**
