### PR TITLE
Update de-DE.coffee

### PR DESCRIPTION
**Pull request by Hahlh**
Rechtschreibfehler verbessert

### CODE REVIEW

**Comment by Bryukh** [comment]
@Hahlh Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Bryukh** [comment]
Hi @Hahlh , could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Bryukh** [comment]
Closed until CLA signed

**Comment by Hahlh** [comment]
Good day @Bryukh !

Sorry that I missed this message.

I signed the CLA :+1:

**Pull request closed without merging**
