### PR TITLE
Added soldiers,librarian and ninja

### PR DESCRIPTION
**Pull request by GeetikaBatra**

### CODE REVIEW

**Comment by nwinter** [comment]
Cool, thanks @GeetikaBatra–can you sign the [CLA](http://codecombat.com/cla) so I can merge this in?

**Comment by GeetikaBatra** [comment]
@nwinter Done :)

**Comment by GeetikaBatra** [comment]
Thanks!!

**Comment by GeetikaBatra** [comment]
Greetings!!
I was going through the code combat website and just realized that while
logging in,the username and password get concatenated to the URL,shouldn't
these be abstract.
Regards Geetika Batra

**Comment by nwinter** [comment]
What page did you log in from where that happened? I saw this once but couldn't find out why it was happening.

**Comment by GeetikaBatra** [comment]
On the following link http://codecombat.com/editor/campaign/forest,a log In option appears at  bottom of the page. Loging In from here concatenates the user Id and password.
I have been developing asp,net MVC application,where the probable cause of this is the form method being used i.e get or post.
Is this problem because of wrong form method?

**Pull request merged**
