### PR TITLE
Update docker-compose.yml : fix ENOENT err

### PR DESCRIPTION
**Pull request by ZJUSTKIDDING**
Fix docker env ENOENT because of missing or misconfig bower

### CODE REVIEW

**Comment by nwinter** [comment]
@ZJUSTKIDDING can you [sign the CLA](https://codecombat.com/cla) and make that update? Thanks!

**Comment by Sketti385** [comment]
That still does not fix anything.

**Comment by mrfinch** [comment]
> That still does not fix anything.

Can you give me more details on what exactly is the error?

**Comment by mrfinch** [comment]
Ahh, I think it's because Dockerfile hasn't been updated for a while. One change I can see there is to use node 14 which we currently use to build it locally. You can try by updating dockerfile to node 14 otherwise I will try to test it sometime next week @Sketti385

**Comment by Sketti385** [comment]
> Ahh, I think it's because Dockerfile hasn't been updated for a while. One change I can see there is to use node 14 which we currently use to build it locally. You can try by updating dockerfile to node 14 otherwise I will try to test it sometime next week @Sketti385

I tried that, and it gives me the same error. I don't know exactly how to use this, but i think docker should be updated.

**Comment by Sketti385** [comment]
Well I tried that, but i get the following error on the page:

ServiceUnavailableError: Response timeout
    at IncomingMessage.<anonymous> (/coco/node_modules/connect-timeout/index.js:84:8)
    at IncomingMessage.emit (events.js:315:20)
    at Timeout._onTimeout (/coco/node_modules/connect-timeout/index.js:49:11)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by foxracle** [comment]
> I got it working, now I need to figure out how to get the npm install to work without failing.

I really appreciated if you would share me the details how  you got the proxy working. I have the same problem.
and do you figure out how to get the npm install to work now?

thanks!

**Comment by Sketti385** [comment]
The base docker setup no longer works, it almost does, but it says my version is 8.15.1... Mine is exactly 14.

**Review by mrfinch — APPROVED** [review]

**Pull request merged**
