### PR TITLE
better solutions for 2148 and 2147

### PR DESCRIPTION
**Pull request by yaur**
Moved fixupUrl to core utils and gave it a more descriptive name since it now has broader visibility.
Disabled AJAX caching globally which likely fixes other IE weirdness.

### CODE REVIEW

**Comment by differentmatt** [comment]
fixupUri broke the help video eventing.  See https://github.com/codecombat/codecombat/commit/92f070eccaae62dce2ac597e452933e83dd75247.

Where else does removeScheme need to be used?

**Comment by differentmatt** [comment]
How does this fix #2159?

**Comment by yaur** [comment]
Sorry should be 2147.
The general case where we need to strip the scheme is that we are storing a URL in the database and need to be able to use it either from HTTP or HTTPS connections.  Running through IE testing I did run into errors with cross scheme/mixed content, though which of those are from the DB and which are hard coded I cant say at this point.

**Comment by yaur** [comment]
Hrm, that isn't good.  So lets not make it easy to do that in other places.  How do you guys feel about disabling the AJAX caching globally?

**Comment by differentmatt** [comment]
Removing the protocol broke the video player eventing.  It's not necessarily a common problem, or related to caching.

I wouldn't disable ajax caching globally without better understanding the impact.  I also wouldn't disable it globally for non-IE browsers without a clear benefit to other browsers.  Do you know what the global effects would be, and how we'd test this change?

**Comment by yaur** [comment]
Looking at what this changes in chrome.  Primarily the behavior of /db/thang.type I think this is going to be a problem.  *sigh*

**Pull request closed without merging**
