### PR TITLE
tłumaczenia kilku pozycji i jedna literówka

### PR DESCRIPTION
**Pull request by Infotelecom**
GitHub jest mi mało znany więc proszę o wybaczenie braku znajomości zasad

### CODE REVIEW

**Comment by Bryukh** [comment]
@Infotelecom Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Infotelecom** [comment]
Done.

 

 

Łukasz Lech

---
❘❙❚ Infotelecom sp. z o.o.
Tel: 62 5971778,  <http://infotelecom.pl/> http://infotelecom.pl
60-523 Poznań, ul. J.H.Dąbrowskiego 75/65
krs: 0000359061, nip: PL7811853941, regon: 301491114

**Comment by Infotelecom** [comment]
I'm new to GitHub. Does it mean it is accepted? Can I go on?

And is it better to work for a few days on file or commit everyday?

**Comment by Bryukh** [comment]
Hello. Yep, it's enough. You can work as convenient for you. Usually, I process translation PR weekly, sometimes more often.

**Pull request merged**
