### PR TITLE
Cookiekrieger patch 

### PR DESCRIPTION
**Pull request by cookiekrieger**
Just a few translations from EN to DE DE
I

### CODE REVIEW

**Comment by nixel2007** [comment]
Hello!
Sorry, but your comments will be deleted at next sync with en-files.
Also - you could see {change} comments near "blurb"-strings for George, Nick and Scott - this means that you need to check the original eu.coffee and update the translation for this strings.

**Comment by Imperadeiro98** [comment]
@cookiekrieger, thanks for contributing! Could you sign the [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by Imperadeiro98** [comment]
Thanks.

**Comment by cookiekrieger** [comment]
you welcome, I'm sorry about the errors..

**Comment by Imperadeiro98** [comment]
No problem.

**Pull request merged**
