### PR TITLE
Add es6 loader to webpack

### PR DESCRIPTION
**Pull request by AndrewJakubowicz**
Lets us use ES6 for new files and slowly move away from Coffeescript.

### CODE REVIEW

**Comment by AndrewJakubowicz** [comment]
@differentmatt I've converted the vue CLAs component and it works on my local proxy build.
Definitely worth checking if it works on ie11. (If it doesn't we can tweak the babel config)

**Comment by AndrewJakubowicz** [comment]
Thanks @differentmatt  - Merging!

**Comment by differentmatt** [comment]
Cc @sderickson :)

**Comment by basicer** [comment]
🎉

**Comment by Bryukh** [comment]
Hooray! Only one thing could be better -- if replace coffeescript in the game engine (referee, systems, components)

**Comment by differentmatt** [comment]
One step at a time @Bryukh 🌱

**Comment by sderickson** [comment]
Woohoo! Have fun with ES6 😄

**Pull request merged**
