### PR TITLE
update fr.coffee v0.6

### PR DESCRIPTION
**Pull request by AmounSai**

### CODE REVIEW

**Comment by AmounSai** [comment]
@Bryukh Hello, 
Can u tell me what's wrong here

**Comment by Bryukh** [comment]
Hmm, looks correct. Maybe some fluke. Checking...

**Comment by Bryukh** [comment]
@AndrewJakubowicz could you look? Is it related to last tests for locale or broken NL translations?

**Comment by AndrewJakubowicz** [comment]
@Bryukh
This is fine. These errors are from the Dutch translations which may still be broken in this branch.

**Pull request merged**
