### PR TITLE
translate some new sentences

### PR DESCRIPTION
**Pull request by levlas**

### CODE REVIEW

**Comment by levlas** [comment]
the build failed, is there an issue in my commit? It seemed to me the problem was on CI side...

**Comment by Bryukh** [comment]
Hi, @levlas. Could you sign our [CLA](codecombat.com/cla) so we could accept your pull request?

**Comment by levlas** [comment]
Hello @Bryukh , done :)

**Comment by Bryukh** [comment]
Thanks. Merged.

**Pull request merged**
