### PR TITLE
Update he.coffee

### PR DESCRIPTION
**Pull request by ChaosCat**
+Another update for "he.coffee" file

### CODE REVIEW

**Comment by ChaosCat** [comment]
<h4>Ok here is an update:</h4>
The site just updated and I found that the percentage went up from <strong>8%</strong> to <strong>41%</strong>, yay! :clap: :clap: :clap:  more than I expected.
but the point is that all the punctuation points were all messed up (and I found some miscorrections here and there while testing the site , especially from the original translation which I suspect being inspired too much by :no_entry: Google translate :no_entry: .
so I will start organizing all these after I finish translating the entire game.
meanwhile I will keep progressing until I get the 100%.
<strong>P.S</strong>: another good news, I am already having demand for the game to be localized in hebrew and arabic so they can teach coding through it at schools here. just pumping me up and make me willing to work harder :smiley:

**Comment by nwinter** [comment]
Great work, @ChaosCat! It's awesome that you're seeing this demand. I think your translations will help a ton of players!

**Comment by ChaosCat** [comment]
could anyone merge this pull request so I can work on the next update please?

**Comment by nwinter** [comment]
Sure!

**Comment by ChaosCat** [comment]
Thanks.

**Pull request merged**
