### PR TITLE
Responsive home page

### PR DESCRIPTION
**Pull request by sderickson**

### CODE REVIEW

**Comment by ryang217** [comment]
@sderickson - a few notes:

1. The "Classroom Edition" and "Learn to Code" labels on the smaller-responsive jumbotron should be h6: 

`<h6 class="col-xs-8">Classroom Edition:</h6><h6 class="col-xs-4">Learn to code:</h6>`

2. On the top nav, preference for alignment is for the red links to be left-aligned  against the logo and the translation dropdown to be right-aligned against the right side of the window. If this is difficult/impossible, let's just left-align it all (instead of centering the block as it currently appears)

**Comment by differentmatt** [comment]
We shouldn't have 3 lines of menu before collapsing to hamburger icon.

screen shot 2016-02-11 at 1 46 02 pm

**Comment by differentmatt** [comment]
CS 8 tile should be under CS 5 tile when 3 course to a row.
screen shot 2016-02-11 at 1 46 57 pm

**Comment by differentmatt** [comment]
Button text shouldn't extend outside of buttons.
screen shot 2016-02-11 at 1 47 59 pm

**Comment by differentmatt** [comment]
Programming languages text should be under the icons as smaller widths, instead of wrapped as in this screenshot.
screen shot 2016-02-11 at 1 49 47 pm

**Comment by differentmatt** [comment]
We should narrow this warning to CodeCombt gameplay, rather than everything:
https://github.com/codecombat/codecombat/blob/responsive-home-page/app/templates/new-home-view.jade#L7

`CodeCombat gameplay was not designed for mobile devices and may not work well!`

@ryang217 what do you think?  Should this warning show up closer to gameplay, instead of immediately on the homepage?

**Comment by ryang217** [comment]
Agree, warning seems unnecessary on homepage and most other pages outside the game itself.

**Comment by differentmatt** [comment]
Bottom footer should split up into 3 distinct pieces when very narrow, instead of wrapping all together.  Text, logo, text.
screen shot 2016-02-11 at 3 48 51 pm

**Comment by ryang217** [comment]
The home icon lost some of its nice padding-right in the latest rev: 
bad_spacing

This is what it is currently on /home, which is what it should be again:
good_spacing

**Pull request merged**
