### PR TITLE
Update zh-HANT.coffee

### PR DESCRIPTION
**Pull request by ArthurLu**
update the part of general

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hi, @ArthurLu! Thanks for your translations.

**Comment by ArthurLu** [comment]
Hi, @Imperadeiro98 . Did you know the reason why I could not correctly merge my commit?

**Comment by Imperadeiro98** [comment]
What do you mean?

**Comment by ArthurLu** [comment]
I mean that I always get "Failure: The Travis CI build failed"

**Comment by Imperadeiro98** [comment]
Yeah, it is not working correcly for any commit at the moment.

**Pull request merged**
