### PR TITLE
More norwegian translations.

### PR DESCRIPTION
**Pull request by mogsie**

### CODE REVIEW

**Comment by mogsie** [comment]
Line 542 was untouched by me...

**Comment by Imperadeiro98** [comment]
Hello, @mogsie! Thank you for contributing. Could you sign the [CLA](https://codecombat.com/cla) so that I can merge your pull request?
Btw, you missed a " at the end of line 412, so it is giving you errors.

**Comment by mogsie** [comment]
Um, did I break the build?

**Comment by mogsie** [comment]
@nwinter "10 Feb 20:50:27 - error: Linting of 'app/locale/nb.coffee' failed. error: coffeescript_error at line 566.  ; Linting of 'app/locale/nb.coffee' failed. error: coffeescript_error at line 566. "  (travis build)

**Comment by popey456963** [comment]
````
    cla_url: "CLA"
    cla_suffix: "."
    cla_agree: "JEG AKSEPTERER"
  contact:
````
with cla_agree: "..." being line 566

**Comment by mogsie** [comment]
But it broke...  Drat!!!!  The previous failure was a missing " a long way up...  urgh.

**Comment by nwinter** [comment]
I fixed this right after that in the latest master (when merging in the other nb.coffee PR); should be fine now.

@popey456963 I think you must have an old version still.

**Comment by mogsie** [comment]
Ah, thank goodness! :+1: :heart: Will continue relentlessly!

**Pull request merged**
