### PR TITLE
Translate zh-HANS.coffee

### PR DESCRIPTION
**Pull request by ExDevilLee**
Translate some new items in zh-HANS.coffee

### CODE REVIEW

**Comment by ExDevilLee** [comment]
@sderickson 
Sorry, but I don't know why "The Travis CI build failed"?  
Could you help me find the reason? 
Thanks!   :-)

**Comment by ExDevilLee** [comment]
@sderickson I have another question about this PR, would The Travis CI  checks it again?

**Comment by Bryukh** [comment]
Looks like it happens for all diplomat patches.

**Comment by ExDevilLee** [comment]
Also failed!!! :-(

**Comment by sderickson** [comment]
Ran it again and it passed this time. A bit finicky, those client tests!

**Comment by ExDevilLee** [comment]
@sderickson Thanks!

**Comment by ExDevilLee** [comment]
@Bryukh Yes, I'm already sign it, thanks for your help!

**Comment by ExDevilLee** [comment]
The Travis CI build failed, at job log 1290 lines I saw the error message: 

> Firefox failed 2 times (timeout). Giving up.

**Comment by ExDevilLee** [comment]
@Bryukh Can you merge this pull request recently?

**Comment by Bryukh** [comment]
@ExDevilLee I can't find you github nickname in the list of people who have signed CLA. Are you sure that you signed it and wrote the right github username?

**Comment by ExDevilLee** [comment]
@Bryukh Yes, I'm sure that I had been signed it and wrote the right github username(ExDevilLee). So, please find again, thanks.

**Comment by Bryukh** [comment]
I don't see your name on the list. Could you try to sign it again, please?

**Comment by ExDevilLee** [comment]
@Bryukh I tried signed it again and I send you e-mail about result with screen capture.  :-)

**Comment by Bryukh** [comment]
Thanks. I see. You've signed it on the "cn" server and it has own database.

**Pull request merged**
