### PR TITLE
Update it.coffee

### PR DESCRIPTION
**Pull request by Atomk**
Just fixed tons of typos and bad translations, more fixes to come (this file is huge)

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @Atomk! Thank you for contributing. Could you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by Atomk** [comment]
I signed the CLA, but...isn't this an open source project? Why do you need a CLA? I never had to sign something to contribute, I'm just curious.

**Comment by Imperadeiro98** [comment]
Thanks, @Atomk! The CLA just gives us the right to use your content. Personally, I'm not much into this kind of topic, but I guess it might necessary for some reason :b (I'm not the owner of the project).

**Comment by Atomk** [comment]
Okay, thanks for the info! See you on the next pull request :)

**Comment by Imperadeiro98** [comment]
Looking forward to see you again, too.

**Pull request merged**
