### PR TITLE
Update he.coffee

### PR DESCRIPTION
**Pull request by ChaosCat**
finished the essentials and I took my time to check the translation, I wasn't active since I worked onmy projects now the steps remaining are
1) finishing the miscellenious translations (teachers, community, editors etc...)
2) fixing the right to left problem (probably by just using the mechanics of the text editor differently[reorganizing brackets, dots, commas, language mixed sentences and so on...])
3) altering other files to support sending the subscription message according to user's gender since there is no way to representboth gender in the same form (Could you please direct me to the files that I need to edit to send the message?)

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Thanks, @ChaosCat! Great job.

Which subscription message are you referring to?

**Comment by ChaosCat** [comment]
I am reffering to the parents subscription e-mail, I thought about adding a simple if statement that sends the right message according to the user's gender variable but that means that I need to add an extra few lines for translation in each of the language files so it won't break with other languages, but in alot of languages the gender differ so I think it will be helpful for a lot of translators

**Comment by ChaosCat** [comment]
the "send your parents an e-mail so they can purchase a subscription for you"

**Comment by Imperadeiro98** [comment]
@nwinter, could you take a look at this issue?

**Comment by nwinter** [comment]
@ChaosCat I wish we knew the user's gender more often, but unless they logged in from Facebook or have been playing for more than four days, we do not know. There's really know way to do it without knowing the gender?

**Comment by ChaosCat** [comment]
@nwinter , I am afraid there is no way to do it generally unless I add a backslash with each gender split which I tried and it looks really awful it would also double the amount of text for no real reason.
I though about 2 solutions <i>(the first one can act as a place holder while the second is written in comments until it's complete)</i>:

<b>1)</b> Adding an option when clicking the <b>"send parents a message"</b> button to select the gender form of the message that you wish to be sent.

<b>2)</b> Adding a gender option to the game that can be changed through registiration for new users and/or profile settings for existing users which will be used for a lot to make the game more comfortable and also will make it easier if you plan releated future updates.

it can also affect the defaults for each gender like the hero gender, the NPCs etc... (but this is just suggestions for later)

P.S: I am glad to help at anything I can here, although my programming speciality is in Java and C++ languages, I do have a basic knowlege of web languages like PHP and Javascript so I think that with some documentation I can manage to pull off this addition (but I am afraid I can't help much with the design of the dropdown menu and the buttons/radio boxes because of my insufficent knowlege in HTML and CSS.

**Comment by nwinter** [comment]
Hmm. We have a poll for asking the user's gender, but we find it much more important to ask about age on the first day, and don't want to be too pushy with the demographics before this email is sent (after level 4). Plus, there's always the option not to answer one's gender, or for transgendered players. I really think that even though it looks bad, we'll have to go with something gender-ambiguous.

**Pull request merged**
