### PR TITLE
Actualizando(Update)

### PR DESCRIPTION
**Pull request by FedericoTomas**
Actualice un poco.

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hi, @FedericoTomas! Thank you for contributing. Could you sign the [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by FedericoTomas** [comment]
Done my friend for 2nd time, i did it on december yet

**Comment by Imperadeiro98** [comment]
My bad! Sorry for making you sign it twice.

**Comment by FedericoTomas** [comment]
Haha, its ok!! No problem, we will end soon the translate

**Pull request merged**
