### PR TITLE
Remove name from loadModel

### PR DESCRIPTION
**Pull request by Imperadeiro98**
I think I got them all.

### CODE REVIEW

**Comment by sderickson** [comment]
Looked through the code and couldn't find any left. Travis client tests fail always on Travis right now, but running them locally where they should all still work, a couple of them fail for the LevelLoader. Please fix these tests first. To run them, see [the instructions in the wiki](https://github.com/codecombat/codecombat/wiki/Testing). Thanks!

**Comment by Imperadeiro98** [comment]
@sderickson, I don't have much experience with tests, and I don't think I'm able to fix them. Can you fix them yourself, please :pray:?

**Comment by sderickson** [comment]
Now's the time to get some experience! ;) They're there to make it so all developers working on the project can easily debug their changes, and it's not surprising these wide-ranging changes would cause a few. All you have to do is navigate to [[http://localhost:3000/test]], click a broken test, then debug as is normal in programming. The page will refresh with every change you make, automatically running any changes you make or displaying the logs you add to the affected area. Give it a try! If it gives you guff, let me know, I want to make testing as easy, painless and useful as possible.

**Comment by Imperadeiro98** [comment]
Ok. I will give it a try then. Thanks for the encouragement :+1:

**Comment by Imperadeiro98** [comment]
From the debugging I made, I found that the change to [line 133](https://github.com/codecombat/codecombat/blob/master/app/lib/LevelLoader.coffee#L133) makes [this test](https://github.com/codecombat/codecombat/blob/master/test/app/lib/LevelLoader.spec.coffee#L105) fail and the change to [line 253](https://github.com/codecombat/codecombat/blob/master/app/lib/LevelLoader.coffee#L253) makes [this other test](https://github.com/codecombat/codecombat/blob/master/test/app/lib/LevelLoader.spec.coffee#L172) fail. I've tried to change the code, but the tests continue to fail.

**Comment by sderickson** [comment]
What happens if you undo the changes to SuperModel and LevelLoader? Do the broken LevelLoader tests pass then?

**Comment by Imperadeiro98** [comment]
Yeah, all the tests work fine. Want me to revert the changes to those files?

**Comment by sderickson** [comment]
Yeah, I think that's going to take more effort to migrate properly. Let's just get the rest of those changes incorporated. Thanks!

**Pull request merged**
