### PR TITLE
updateLevelRequiredItems: special-case rings, fixes #2740

### LINKED ISSUE #2740: The Geometry of Flowers - With only one ring
It seems like it's impossible to play The Geometry of Flowers without having brought a separate ring.
Both ring slots need to be filled to play the level and that doesn't make sense.

### PR DESCRIPTION
**Pull request by UltCombo**
Rings often have unique effects instead of progressively enhancing another ring's effect, hence let's make rings required even if there's already non-restricted rings equipped.

If, by any chance, there's ever a new ring which enhances the effect of a ring which is required for some level, then it should be easy enough to whitelist it in the given ring slot's allowed items array.

### CODE REVIEW

**Comment by nwinter** [comment]
So smart! I love having your fresh eyes on things; of course that's the case for rings. Thanks for just cutting straight through all the delirium around that!

**Comment by UltCombo** [comment]
It is no problem, really. :smiley:
If I may say so, I find it more fun to hack at the game's core than playing the game itself. :smile_cat:

**Comment by nwinter** [comment]
... I love you. Also, to show my love, I have laid out a stunning repast of delicious issues on this issue tracker for you to feast upon.

**Comment by UltCombo** [comment]
Ahahah :smile:
I have a 40-hour work week as a Web developer (which is often quite exhausting) and a few other projects to maintain, but I'll try to submit fixes every now and then. :beers:

**Pull request merged**
