### PR TITLE
Update hi.coffee

### PR DESCRIPTION
**Pull request by divyanshu013**

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hi, @divyanshu013! Will you finish lines 45 and 46, or should I merge?

**Comment by divyanshu013** [comment]
@Imperadeiro98 I'll finish them and add some more but you may merge if you wish.

**Comment by Imperadeiro98** [comment]
I can wait.

**Comment by divyanshu013** [comment]
Sure, no problem :)

**Comment by divyanshu013** [comment]
Looks good for a merge now @Imperadeiro98

**Comment by Imperadeiro98** [comment]
Thanks.

**Pull request merged**
