### PR TITLE
Update sr.coffee2

### PR DESCRIPTION
**Pull request by ana-esova**
- translated buy_gems, subscribe, options and about sections
- fixed a couple of lines in other sections and added some missing translations

\+ calendar section in my second commit

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Awesome job, @ana-esova. Thank you :+1:

@nwinter

**Comment by Imperadeiro98** [comment]
@nwinter

**Comment by ana-esova** [comment]
@Imperadeiro98 should I make a new pull request for these translations since there have been new lines added in the locale file?

**Comment by Imperadeiro98** [comment]
If you can open a new pull request without merge conflicts, I would appreciate. Thanks.

**Pull request closed without merging**
