### PR TITLE
Full translation of the file in Greek

### PR DESCRIPTION
**Pull request by Bacilic**
There were **1550+** changes to the file! I hope there are _no syntax errors_ and _correct use of the variables_.
I hope soon to see all codecombat in Greek language. I look forward to the result.

### CODE REVIEW

**Comment by Bryukh** [comment]
Could you sign our [CLA](http://codecombat.com/cla) so we can accept your PR? I'll check your translation and fix syntax if there is an error.

**Comment by Bacilic** [comment]
I accepted the Contributor License Agreement.

I've found the error (which I think is the only one) in line 40. Two words with quotation marks, I have used " instead of “”

**Comment by Bacilic** [comment]
Thanks for the fixes.

When will the file be updated to see the translation live for any corrections?

**Comment by Bryukh** [comment]
@Bacilic I've found more errors. When CI approve the commit I'll merge it.

**Comment by Bryukh** [comment]
Looks ok. Thank you for the huge translation. I can only guess how long it has taken for you.

**Comment by Michael18811380328** [comment]
Well done ! Thank you for the translation in Greek language during such a short time.

**Comment by Bacilic** [comment]
It worthwhile.
Around 30 hours, about 5 hours for day!
Now the **translation page** are the next...

**Comment by nwinter** [comment]
@Bacilic wonderful, thanks for your heroic contribution!

**Pull request merged**
