### PR TITLE
Upgraded ace editor to 1.4.x for better mobile support

### PR DESCRIPTION
**Pull request by iainbeeston**
ISSUE
-----

Right now it's not possible to use the editor on iOS. Although no javascript errors are thrown, the editor does not appear, making code combat unusable.

Here's what it looks like (note that the editor isn't visible and can't be used):

before_small

SOLUTION
------

Code combat is using ace editor version 1.2.9, which is rather old and doesn't have good mobile support. There have been a lot of improvements for mobile in version 1.4, and upgrading to ace editor 1.4.5 makes it work perfectly on iOS with no code changes.

Here's what it looks like with the latest ace editor (see that the editor is working as it does on desktop):

Screenshot 2019-08-13 at 15 16 54

These are the [changes](https://github.com/ajaxorg/ace/blob/d893a99a8bb317440080bd766288da4e8a7e9524/ChangeLog.txt) in ace editor between versions 1.2.9 and 1.4.5:

```
2019.06.17 Version 1.4.5
* improve scrolling and selection on mobile 
* improve type definitions

2019.04.24 Version 1.4.4
* add experimental command prompt
* add chrystal, nim and nginx highlight rules
* fix regression in vim mode on ios

2019.02.21 Version 1.4.3
* add sublime keybindings
* add rtl option
* implement ` and < textobjects in vim mode

2018.11.21 Version 1.4.2
* fix regression in vim mode
* improve keyboard input handling on ipad and IE
* add new syntax highlighters

2018.08.07 Version 1.4.1
* fix regression in autocomplete

2018.08.06 Version 1.4.0

* remove usage of innerHTML
* improved handling of textinput for IME and mobile
* add support for relative line numbers
* improve autocompletion popup 

2018.03.26 Version 1.3.3
* fix regession in static-highlight extension
* use css animation for cursor blinking

2018.03.21 Version 1.3.2
* add experimental support for using ace-builds with webpack

2018.02.11 Version 1.3.1

* fixed regression with selectionChange event not firing some times
* improved handling of non-ascii characters in vim normal mode

2018.01.31 Version 1.3.0

* added copy copyWithEmptySelection option 
* improved undoManager
* improved settings_menu plugin
* improved handling of files with very long lines
* fixed bug with scrolling editor out of view in transformed elements
```

### CODE REVIEW

**Comment by AndrewJakubowicz** [comment]
Hi @iainbeeston ,

We've sadly had to revert this commit due to a bug found recently.
Bug video link: https://www.youtube.com/watch?v=5wmOSZJOooo

Would you like to tackle the bug?

Thanks!

**Comment by iainbeeston** [comment]
Unfortunately I cannot reproduce the bug! I've tried both the original branch and the master branch right before this PR was reverted and it works fine in both the latest firefox and the latest chrome. I've even tried changing my language to Russian to see if that would produce the same effect but it still works.

Here's a video of what I see:

https://youtu.be/fr8N7nOnFA8

Unfortunately I can only test on mac, not windows or linux, so it's possible that it the only place it works is on mac? The only other thing I can suggest is perhaps it was a temporary caching issue for this user, but that seems unlikely.

Unfortunately if I can't reproduce the problem I have no way to start debugging it or fixing it. Hopefully rolling back will fix the problem for your users but it also means that the code combat editor will not work on touch-based devices for now

**Comment by AndrewJakubowicz** [comment]
Would you be able to try a tab indent and see if that reproduces the issue?

Something like:

```
if:
    hero.walkLeft()
```

^ This isn't any sort of legal syntax but should cause the issue.

**Comment by iainbeeston** [comment]
@AndrewJakubowicz That does it! It turns out as soon as you type `if:` it hits a javascript error:

```
SpellView.coffee?e38a:355 Uncaught TypeError: Cannot read property 'push' of undefined
    at Object.aceSession.addDynamicMarker.update (SpellView.coffee?e38a:355)
    at Marker.update (ace.js?cb83:16209)
    at VirtualRenderer.$renderChanges (ace.js?cb83:18789)
    at RenderLoop._flush (ace.js?cb83:17374)
```

Looking at the code, it's failing on [this](https://github.com/codecombat/codecombat/blob/379fb5983fddf90b7764a96f10a5ef9728638b81/app/views/play/level/tome/SpellView.coffee#L355) line, because the `html` variable is `null`. It seems that the ace api changed in 1.4 so that the variable is always `null` for the `addDynamicMarker` callback. I've had a look on google and I can see someone else had the same issue ([here's](https://github.com/ajaxorg/ace/issues/3874) the github issue and [here](https://github.com/convergencelabs/ace-collab-ext/commit/5bf73550bd1b04628200087d8b7e46e18e92c488#diff-b0bdcb19f2e3c0d26b1f4b686a68070bL53) is the fix). I can also see now why the issue only appears in Python and not JavaScript, because we never reach that bit of code for any language other than javascript (see [here](https://github.com/codecombat/codecombat/blob/379fb5983fddf90b7764a96f10a5ef9728638b81/app/views/play/level/tome/SpellView.coffee#L328)).

What the code that fails is doing is to highlight any indentation in blue, which is useful in Python as it is whitespace sensitive.

**Comment by iainbeeston** [comment]
I've spent a few hours trying to fix the issue. You can see my attempt [here](https://github.com/codecombat/codecombat/compare/master...iainbeeston:upgrade-ace-editor). It fixes the reported issue, but has it's own bug, which is that when you select some code, the rectangles that highlight whitespace are duplicated and move with the cursor. You can see what I mean in this video:

https://youtu.be/_UBm2k_xBe0

It's a strange issue and I haven't been able to figure out what is causing it. It looks like something is duplicating the `<div>`s added by the dynamic marker, and then adding them as children to the `<div class="problem-marker-warning">` tag. If I could see what makes the this problem marker tag I might be able to fix it (looks like it might be created from a `Problem` object?).

The one other thing I've learned is that the code we had before did not work for two reasons:

1. It used the `html` parameter of `createDynamicMarker` (which is `null` in ace 1.4)
2. We were adding our divs as children of ace's marker layer node. It seems that in ace 1.4 you cannot do that (ace seems to rewrite the marker layer during render), so instead I've added our divs as grandchildren, using the `markerLayer.elt()` method (which is undocumented but seems to provide us with a "blessed" child node) and this allows us to add our own content without it being overwritten.

I hope that's helpful, but unless someone can suggest what might be causing my bug I'm not sure what else I can do about this

**Comment by AndrewJakubowicz** [comment]
This is extremely helpful! I'll take a better look on Monday and see if I can suggest or figure out a workaround to the bug you showed in the youtube video.

Thank you so much!

**Comment by iainbeeston** [comment]
Wonderful! Hearing that makes all the time I spent on it worthwhile 🙂

**Comment by AndrewJakubowicz** [comment]
Hey @iainbeeston 

Thank you so much for all the information you provided and researched. I took a look and made some minor changes and I think it resolved the issue you were seeing!

My attempt to fix your issue: https://github.com/codecombat/codecombat/commit/45947cb0ee6141b053c4e69416c7f1ab22547399

Sharing with you to see if this fixes your issue, and whether you'd like to open a similar PR to merge the update and fix into CodeCombat?

Thank you!

**Pull request merged**
