### PR TITLE
[Translate fil-PH] **DO NOT MERGE YET**

### PR DESCRIPTION
**Pull request by Celestz**
- [x] new_home area
- [ ] nav
- [ ] modal
- [ ] not_found
- [ ] diplomat_suggestion
- [ ] play
- [ ] code
- [ ] share_progress_modal
- [ ] login
- [ ] signup
- [ ] recover
- [ ] items
- [ ] common
- [ ] general
- [x] units
- [ ] play_level
- [ ] play_game_dev_level
- [ ] game_menu
- [ ] leaderboard
- [ ] inventory
- [ ] buy_gems
- [ ] subscribe
- [ ] choose_hero
- [ ] skill_docs
- [ ] save_load
- [ ] options
- [ ] about
- [ ] teachers
- [ ] special_offer
- [ ] teachers_quote
- [ ] versions
- [ ] account_settings
- [ ] keyboard_shortcuts
- [ ] community
- [ ] clans
- [ ] courses
- [ ] teacher
- [ ] sharing
- [ ] game_dev
- [ ] web_dev
- [ ] classes 
- [ ] editor
- [ ] article
- [x] polls - No Translation Required
- [ ] contribute
- [ ] ladder
- [ ] user
- [ ] achievements
- [ ] account
- [ ] account_invoices
- [ ] account_prepaid
- [x] coppa_deny
- [ ] loading_error
- [ ] resources
- [ ] concepts
- [ ] delta
- [x] legal
- [ ] ladder_prizes XX - Not Needed
- [x] calendar

### CODE REVIEW

**Comment by Celestz** [comment]
Do not merge yet, this is a work in progress for Tagalog(Philippines).
I'll be updating this on my free time.

**Comment by nwinter** [comment]
Awesome, thanks for your work to add a new language!

You will want to uncomment the lines that are translated by removing the `#` at the beginning of those lines, and remove the `#` from any section headers where at least one translation is present.

Also, let's call this file just `fil.coffee`, since we can't be as specific as `fil-PH` without multiple language families, and at least in Chrome, my browser is just setting `fil`.

To fully accept it, we'll also need to add it to [locale.coffee](https://github.com/codecombat/codecombat/blob/master/app/locale/locale.coffee#L37) and [DiplomatView.coffee](https://github.com/codecombat/codecombat/blob/master/app/views/contribute/DiplomatView.coffee#L63) in two places. That should be enough to test locally, if you are interested.

**Comment by Celestz** [comment]
my last commit caused the build to fail, wonder what the issue was.

**Comment by Celestz** [comment]
nvm, I see it, fixing.

**Comment by nwinter** [comment]
Should we get this in there now so that new users can start using/seeing the translations?

**Comment by Celestz** [comment]
@nwinter I'm game, I currently got busy so will be dropping by here and there to take a shot, but if anyone wants to help I'm up for it.

**Pull request merged**
