### PR TITLE
Update tr.coffee

### PR DESCRIPTION
**Pull request by iammehmetguler**
nav, modal, general, play_level, about

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
@iammehmetguler, can you open a new pull request with only the last commit (the one that has the relevant changes)? Thanks

**Comment by iammehmetguler** [comment]
@Imperadeiro98, sure. how can i open a new pull request with only the last commit?

**Comment by nachein** [comment]
@iammehmetguler one way could be creating a new branch out of the latest master and cherry pick the last commit (#2b72fd0)

**Comment by Imperadeiro98** [comment]
@iammehmetguler, are you available to finish this pull request?

**Pull request closed without merging**
