### PR TITLE
Update es-ES.coffee

### PR DESCRIPTION
**Pull request by duhow**
Added some new translates and changes.

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @duhow! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by duhow** [comment]
@Imperadeiro98 Done!

**Comment by Imperadeiro98** [comment]
@nwinter, can you merge this PR?

**Comment by ilo** [comment]
Hi Duhow!

Looks like we had the same idea at the same time. I think it is easier to provide smaller patches, it makes rollback faster and can be easily reviewed.

Also, I've found some 'wording' issues in this patch. E.g. on certain pages 'payments' has already been translated as 'Pagos', and you are using 'Facturas'. Worths to check previous commits or other sentences to build a common wording guide.

I was about to start doing it and then I saw your PR. Do you want to split tasks?

**Comment by nwinter** [comment]
Thanks @duhow!

**Pull request merged**
