### PR TITLE
#3138 #3488 refactor CampaignView - rebased

### PR DESCRIPTION
**Pull request by duybkict**

### CODE REVIEW

**Comment by duybkict** [comment]
Is there any issue with Travis, I got this error `The command "./node_modules/karma/bin/karma start --browsers Firefox --single-run --reporters dots" exited with 1.`

**Comment by sderickson** [comment]
Reran the tests, worked this time.

Needs to handle [this weird loading issue](https://github.com/codecombat/codecombat/pull/3739#discussion_r67725874)

**Comment by sderickson** [comment]
@duybkict are you available to wrap this PR up?

**Comment by sderickson** [comment]
Closing due to inactivity

**Pull request closed without merging**
