### PR TITLE
Update he.coffee

### PR DESCRIPTION
**Pull request by ChaosCat**
a minor update for he.coffee

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Thank you, @ChaosCat!

**Comment by ChaosCat** [comment]
Glad to help, by the way is there a way to see the percentage of translation through gitHub? (The site hasn't updated yet) and a simple way to track the progress would be really helpful

**Comment by Imperadeiro98** [comment]
Not that I know. You will have to wait until it is live.

**Comment by ChaosCat** [comment]
Ok thanks.

**Pull request merged**
