### PR TITLE
Update ca.coffee

### PR DESCRIPTION
**Pull request by Nainufar**
some more translations and some corrections

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @Nainufar! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by Nainufar** [comment]
Done. Is for this reason that check failed?

**Comment by Imperadeiro98** [comment]
No, the failure has nothing to do with the changes you made

**Comment by Nainufar** [comment]
Thanks for merge it @Imperadeiro98. I haven't understood you. I'm new to GitHub and I don't know why appeared me the message " 1 check failed. continuous-integration/travis-ci/pr The Travis CI build failed". Can you tell me why? Thanks you.

**Comment by Imperadeiro98** [comment]
Sure. When a build runs, some tests are made to the code and sometimes, like in this case, some of them fail. But the fail is related to other parts of the code that you didn't touch, so, you did nothing wrong. What failed is listed in https://travis-ci.org/codecombat/codecombat/builds/96595542#L6529. Hope you understand :)

**Pull request merged**
