### PR TITLE
Added a "god mode" button to the local dev environment  (issue #2164)

### PR DESCRIPTION
**Pull request by laituan245**
I have added a checkbox that can be used to turn on the "god mode". (#2164)

screenshot from 2015-02-14 01 37 41

If you turn on the "god mode" then: 
+ You will become a premium user 
+ You can play all the levels (including preminum levels)
+ You will receive 100000 gems  (but if you turn off the "god mode" then you lose those gems)
+ You will receive 1000000 xp points (if you turn off the "god mode" then you lose those xp points)
+ All the heroes are unlocked 

screenshot from 2015-02-14 01 38 02

### CODE REVIEW

**Comment by nwinter** [comment]
Ah, this is great–really nice work on this!

**Comment by Warlock900** [comment]
can you please do "God Mode" for my account? I really want to try all the characters and all the levels. Thank-you.

**Comment by nwinter** [comment]
Sorry @Warlock900, can't activate God Mode on the main codecombat.com server–that'd be cheating! ;)

**Comment by Warlock900** [comment]
Can you let me run my own server on CodeCombat?

**Comment by nwinter** [comment]
You can run your own CodeCombat local server as described in the [dev setup instructions](https://github.com/codecombat/codecombat/wiki/Dev-Setup:-General-Information), but you have to create your own levels for it, since we don't include all the levels in the testing database dump, which kind of defeats the point of god mode.

**Comment by Warlock900** [comment]
thank-u

**Pull request merged**
