### PR TITLE
Update ja.coffee

### PR DESCRIPTION
**Pull request by Coderaulic**
Some minor fixes added based on last changes.
Can you tell me how to add a line break?
Is it " text \ text " for:
text
text
as output? Or "ABC '\' DEF" for:
ABC
DEF
Not familiar with line breaks in coffee script.

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Thank you, @Coderaulic.

Regarding line breaks, I don't know if they are possible. Why would you need to use them?

**Comment by Coderaulic** [comment]
So in line 6: it has it as "ゲームスタート" ("Start Game").
In the browser is shows as 
"ゲームス
タート"
which is hard to read as 
"Start G
ame"
I wanted to put a line break so that it should show as 
ゲーム
スタート
If it is not possible, I think changing it to
 "スタート" (Start) or 
"プレイ"(Play)

**Comment by nwinter** [comment]
Just tried it out, and although we aren't able to make that sort of line break happen just with the translations, you can put <br> or other HTML in a translation if it is used along with `data-i18n="[html]home.play"` like in 88c55fa.

**Comment by Coderaulic** [comment]
HA! The <br> did it. I will keep that in mind. Thanks.

**Comment by Coderaulic** [comment]
LOL! "<<B.R>>" did it.

**Pull request merged**
