### PR TITLE
translate Chinese

### PR DESCRIPTION
**Pull request by Michael18811380328**
i want to translate much Chinese, however the Travis CI test tell me there are much errors. So this is test PR to translate.

### CODE REVIEW

**Comment by Bryukh** [comment]
@Michael18811380328 Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Michael18811380328** [comment]
I have sign CLA and my account is Michael18811380328

**Comment by Michael18811380328** [comment]
@Bryukh Thank you.

**Comment by Bryukh** [comment]
Thanks! Merged.

**Pull request merged**
