### PR TITLE
Remove a lot of unused strings

### PR DESCRIPTION
**Pull request by Imperadeiro98**

### CODE REVIEW

**Comment by nwinter** [comment]
We need those resources strings; they are loaded by lines like this:

```coffeescript
@sessions = @supermodel.loadCollection(new LevelSessionsCollection(), 'your_sessions', {cache: false}, 0).model
```

Can you update to re-include those?

The rest look good except I don't know if we were about to put back in the three about teachers selecting languages/progress; @sderickson?

**Comment by Imperadeiro98** [comment]
Could you explain how the strings are called by this lines (if it doesn't give you much work nor takes much of your time)?

**Comment by nwinter** [comment]
Sure. In [the SuperModel](https://github.com/codecombat/codecombat/blob/master/app/models/SuperModel.coffee#L217-L217), the resources to load store their names (which match these i18n strings). Then if the load fails for some reason, the CocoView listening to that resource to load [handles the error](https://github.com/codecombat/codecombat/blob/master/app/views/core/CocoView.coffee#L154-L175) by creating a loading error message from the [loading error template](https://github.com/codecombat/codecombat/blob/master/app/templates/core/loading-error.jade#L4-L4), which displays this line:

```jade
span(data-i18n="resources.#{name}")
```

**Comment by Imperadeiro98** [comment]
Thanks for the explanation :)

**Pull request merged**
