### PR TITLE
A few tip translations

### PR DESCRIPTION
**Pull request by tuomastanner**

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @tuomastanner! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by tuomastanner** [comment]
CLA signed. I translated a few tips, but could not find the objective strings to translate. For example:
Villagers must survive
Bonus: no code problems

These strings are much more important to my kids which don't speak English yet. 
I search for these in the project but could not find them. Are they part of a different project / your proprietary levels? If so, could you maybe add the strings to the localization files and reference those instead of having them hard coded in English.

I'd love to translate those!

**Comment by tuomastanner** [comment]
AH! found the level translation editor through a forum post: http://codecombat.com/i18
Somehow I missed it on the diplomat page and went straight to github :)

**Comment by tuomastanner** [comment]
BTW just translated the second Gems in the Deep level and found out that there is an Overview section that gives a lot of useful info on completing a level. For example that you can give the movement functions parameters! I had not discovered this nor had any of my three boys.

I went hunting for it in the level and found it under the Game menu -hamburger menu. Not discoverable at all. Maybe a separate Tips / Overview -button could be added to the main level page next to the code?

**Comment by Imperadeiro98** [comment]
Hello, @tuomastanner! I'm glad you found the i18n page and thank you for taking the time to translate the levels.
In the levels, there is a 'Help' button bellow the code that takes you to the 'Overview' section.

**Pull request merged**
