### PR TITLE
Update pl.coffee with Polish translation

### PR DESCRIPTION
**Pull request by mloskot**
This is updated version of PR #5954 by @fatherJS
including https://github.com/codecombat/codecombat/pull/5954#discussion_r502900683 suggestion by @harnash

I'm going to make this change CLA signed.

### CODE REVIEW

**Review by harnash — APPROVED** [review]

**Comment by briukhanova** [comment]
Hi @mloskot. Thanks for the translations! So we can merge this in, can you [sign the CLA?](https://contributors.codecombat.com/cla)

**Comment by mloskot** [comment]
Just signed

**Comment by mloskot** [comment]
@briukhanova I have signed the CLA but I'm not sure if I'm supposed to see any status update, the page has neither redirected me nor refreshed the PR details.

image

**Comment by briukhanova** [comment]
@mloskot  Thanks. We've got it.

**Comment by Bryukh** [comment]
Thanks! Merged.

**Pull request merged**
