### PR TITLE
new update 

### PR DESCRIPTION
**Pull request by Ihsara**
new update for vi translation

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @Ihsara! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by Ihsara** [comment]
I've signed it now !! Thanks for reminding me !!

**Comment by Imperadeiro98** [comment]
Thank you!

@nwinter

**Comment by khoa102** [comment]
New Update for vi.coffee Translation

**Pull request merged**
