### PR TITLE
More achievement tweaks

### PR DESCRIPTION
**Pull request by sderickson**
* Clients check updated achievements as well as new ones
* Clients do not wait to keep checking

### CODE REVIEW

**Comment by UltCombo** [comment]
By the way, does this fixes #3214?

**Comment by sderickson** [comment]
It should, once it's fully deployed. This PR will not enable it for everyone; I want to test it more on production on some test accounts first.

**Comment by Bryukh** [comment]
> on some test accounts first.
I can be a guinea-pig. I have many unclosed broken achievments :-)

**Comment by sderickson** [comment]
Actually, going to change my tactic here, make more changes and then deploy.

**Pull request closed without merging**
