### PR TITLE
toggle regular and championship when navigate

### PR DESCRIPTION
**Pull request by smallst**
fix ENG-973
output

gif is not clear, but it's just we only loop regular arena before, adding championship into navigation too

## Summary by CodeRabbit

- **New Features**
	- Introduced conditional logic for better handling of regular and championship leagues.
	- Added a new data property to enhance data management based on league type.
	- Implemented new computed properties for dynamic selection of rankings and player counts.
	- Added a method to check the availability of the championship arena.
	- Enhanced localization support with new labels for tournament types.

- **Style**
	- Improved code formatting by removing unnecessary whitespace in the AILeagueView component.

### CODE REVIEW

**Review by adamkecskes — COMMENTED** [review]
I don't think it's blocking, but to avoid any future typo issue, I'd create constants like 
```
const TYPES = { REGULAR: 'regular', CHAMPIONSHIP: 'championship' }
```

Do I understand correctly that each season has a regular and a championship board?
Users might not understand why is the title not changing when they click the next/prev buttons. Those buttons seem to change season. Why don't we display if it is regular or championship arena? Or maybe there should be two tabs for them to make it clear?

**Review by mrfinch — COMMENTED** [review]
Can we add a string 'REGULAR'/'CHAMPIONSHIP' below the horizontal line of Season X: Name to differentiate the navigation movement

**Review by nwinter — COMMENTED** [review]
This could work. I would have attempted to show both at the same time, since the regular arena ends at the same time as the championship arena, and having both in the same navigation flow suggests a stronger linearity to their ordering. But if we do that, not sure how we can easily support scrolling backwards through the past arenas. Maybe the scrolling includes past championship arenas, but if there's a current championship arena, it lives in its own leaderboard on the teacher dashboard as a third entry, pushing down the CodePoints leaderboard?

Up to y'all, not blocking.

**Comment by mrfinch** [comment]
> This could work. I would have attempted to show both at the same time, since the regular arena ends at the same time as the championship arena, and having both in the same navigation flow suggests a stronger linearity to their ordering. But if we do that, not sure how we can easily support scrolling backwards through the past arenas. Maybe the scrolling includes past championship arenas, but if there's a current championship arena, it lives in its own leaderboard on the teacher dashboard as a third entry, pushing down the CodePoints leaderboard?
> 
> Up to y'all, not blocking.

We could add a toggle 'Regular/Championship' below instead to show that they are related.

**Comment by smallst** [comment]
image
updated

**Review by mrfinch — COMMENTED** [review]
Can we use a switch like this instead: https://skirtles-code.github.io/vue-examples/components/toggle-switch - we can copy the component or use a library which doesn't add too much space to our app bundle

**Comment by mrfinch** [comment]
updated it to this:
Screenshot 2024-08-20 at 12 04 48 PM

**Pull request merged**
