### PR TITLE
Distro-specific devSetup for Arch Linux and Ubuntu

### PR DESCRIPTION
**Pull request by emhs**
There's no good reason to leave mongo and node out in the cold in terms of distro-provided updates. This ensures that Arch and Ubuntu get those. I'll add more distros as requested, or anyone else can. They're pretty easy.

### CODE REVIEW

**Comment by emhs** [comment]
Also, this includes a test to ensure python3 doesn't interfere with node-gyp.

**Comment by popey456963** [comment]
That's great!  Will be extremely useful for anyone installing on Ubuntu/Arch

**Comment by schmatz** [comment]
Great work! The only thing which I am wondering about is whether to start Mongo as a service by default.   @emhs, @popey456963, what do you guys think? If you guys think it's a good move, I'll merge it in.

**Comment by popey456963** [comment]
@schmatz I think that starting Mongo as a service by default is good idea.  Ideally, I'd like to be able to run this script and then be able to work in the development - similar to the Windows version.

**Comment by schmatz** [comment]
We do have a script, `coco-mongodb`, which starts the database. My concern is that people wouldn't want Mongo running all the time as a service, though unless anyone vetoes I'll merge this in. @nwinter, what do you think?

**Comment by nwinter** [comment]
It might help, as long as people don't get confused from our instructions and then think they need to run coco-mongodb but see it die from EADDRINUSE and not know it's already running. So we would just want to update the instructions for using it, I guess.

**Comment by popey456963** [comment]
Alternatively, we could have two separate editions.  Clearly state what they both are, suggest one for less advanced users, the other for advanced users.

**Comment by emhs** [comment]
Strangely enough, coco-mongodb didn't fail on Arch after starting Mongo via Systemd.

**Comment by popey456963** [comment]
Hm, weird :confused:

**Comment by emhs** [comment]
Dropped Mongo autostarting from Arch. Ubuntu starts it automatically post-install.

**Comment by nwinter** [comment]
Nice work, @emhs!

**Pull request merged**
