### PR TITLE
Update lt.coffee

### PR DESCRIPTION
**Pull request by snarkota**
More translation strings

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Good job, @snarkota

**Comment by snarkota** [comment]
Thank you, @Imperadeiro98 

BTW, I would gladly translate some levels too, but for some reason I'translation page at https://codecombat.com/i18n does not start for me. Loading progress bar fills to 100% and then just stays there. I've tested it with Chrome 46.0.2490.71 m (win7 and win10), Edge Browser and IE (win10, win7, IE compatibility mode as well).

Is it a known problem or should I go and submit a ticket (somwhere).. Or maybe I'm just doing something wrong?

Best regards and sorry for offtopic...

**Comment by themaka** [comment]
Hello @snarkota,

Could I ask you to open up your console and tell us what errors you see when you try this?

Here is a link to instructions on how to open the javascript console:
http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers/77337#77337

**Comment by snarkota** [comment]
*templates/i18n/i18n-home-view*
*views/i18n/I18NHomeView*
*app.js:456 loaded 2 files, 12 KB*
**4 (program):20 Uncaught TypeError: Array.prototype.indexOf called on null or undefined**

**Comment by Imperadeiro98** [comment]
I have opened an issue here https://github.com/codecombat/codecombat/issues/3126. Thank you for the bug report.

**Pull request merged**
