### PR TITLE
Update zh-HANS.coffee

### PR DESCRIPTION
**Pull request by Raphaelwuhao**
update some of the translations.

### CODE REVIEW

**Comment by zlydh** [comment]
add some new translations

**Comment by Raphaelwuhao** [comment]
@zlydh where should I find new words that need translation?

**Comment by Imperadeiro98** [comment]
Hello, @Raphaelwuhao! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by Raphaelwuhao** [comment]
@Imperadeiro98 sure, done.

**Pull request merged**
