### PR TITLE
Update de-DE.coffee

### PR DESCRIPTION
**Pull request by Zeldaretter**
i added and translated all lines that where missing from the original English en.coffee

I would like to Copy my changes to the Austrian German version, because it is nearly the same and if some Austrian Translator finds an error or a better word than he can edit it, but its like british and american English and both understand each others well and here I think its better to have German than English, what do you think?

### CODE REVIEW

**Comment by nwinter** [comment]
It should automatically fall-sideways from de-AT to de-DE now (I recently changed this), so if it doesn't find a de-AT translation, it will use the de-DE one before the en one. So I don't think we need to copy and paste. Sound good?

**Comment by Zeldaretter** [comment]
Nice Solution i will change the diplomats string in de-at afterwards
Am 16.03.2016 18:42 schrieb "Nick Winter" <notifications@github.com>:

**Comment by Zeldaretter** [comment]
We should do the same with de-ch too

**Comment by nwinter** [comment]
Yeah, it automatically happens between all `de-*` (or `*-*`) language families!

**Comment by Imperadeiro98** [comment]
Looks good :+1:

**Pull request merged**
