### PR TITLE
Translate into Vietnamese

### PR DESCRIPTION
**Pull request by duybkict**

### CODE REVIEW

**Comment by duybkict** [comment]
Could anyone assist me on this compiling error? There might be some strange syntax error

**Comment by Imperadeiro98** [comment]
Hello, @duybkict ! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

About the error you are seeing, it is because the indentation of some lines is not correct (for example, lines 27-43).

**Comment by duybkict** [comment]
I fixed the tab character issue, but it now seems to have some conflicts. Could you please check it for me as I could not see the errors

**Comment by Imperadeiro98** [comment]
@nwinter

**Comment by duybkict** [comment]
Merged with master and resolved conflicts

**Comment by nwinter** [comment]
Thanks @duybkict! Nice work!

**Pull request merged**
