### PR TITLE
Update pt-BR.coffee

### PR DESCRIPTION
**Pull request by rohmunhoz**
Translated many strings

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @rohmunhoz! Thank you for contributing. Could you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

**Comment by Imperadeiro98** [comment]
Hi, @rohmunhoz! Could you sign our [CLA](https://codecombat.com/cla)? Otherwise, I'll have to close this pull request until you sign it.

**Comment by Imperadeiro98** [comment]
Will reopen if the CLA gets signed.

**Comment by rohmunhoz** [comment]
I'm sorry for the late, but I signed the CLA

**Comment by Imperadeiro98** [comment]
No problem. @nwinter, can you merge?

**Comment by nwinter** [comment]
Thanks @rohmunhoz!

**Pull request merged**
