### PR TITLE
#3138 #3488 refactor UserView

### PR DESCRIPTION
**Pull request by duybkict**

### CODE REVIEW

**Comment by sderickson** [comment]
Going to /user/scott, nothing shows up. Did you test the view in your dev environment after you refactored?

**Comment by duybkict** [comment]
Turn out that this view is closely related to MainUserView, I will refactor both views and submit a fix

**Comment by duybkict** [comment]
I updated my code but there appears to be messed up css on the page, could you please take a look at it for me

**Comment by sderickson** [comment]
Looks like you're getting a good handle of our kinda wonky loading system. Squashed and merged in, thanks! 👍 https://github.com/codecombat/codecombat/commit/4f369a1e2f32ce9a84274f3da6478513bc30f215

**Pull request closed without merging**
