### PR TITLE
Add rest of Duck Images

### PR DESCRIPTION
**Pull request by Chaboi45**
Adds the rest of the duck images:
Screen Shot 2021-07-04 at 11 09 39 AM

### CODE REVIEW

**Review by nwinter — CHANGES_REQUESTED** [review]
I think we can get the filesize way down on these by saving them closer to the size at which they will be rendered, and then also dropping then into an automatic image optimizer (I've been using [ImageOptim](https://imageoptim.com/mac), but there may be better ones).

**Comment by Chaboi45** [comment]
I used my handy image editing app to scale down each of the duck images to around what the 5 current ducks were, but I can try optimizing them further.

**Comment by Chaboi45** [comment]
@nwinter I just ran the images through ImageOptim and uploaded them 👍

**Comment by nwinter** [comment]
This is better, now they're not bigger than the original duck images. But, I think the original duck images were also uploaded too large. We only [display at 100px width](https://github.com/codecombat/codecombat/blob/3df71c9b641bbc9be0e796c5684f4f9ded69461b/app/templates/play/level/tome/problem_alert.jade#L6), so we should probably have all the ducks at 200px width (for 2x resolution screens) instead of the 531-638px width they are in at.

Want to take a crack at resizing them all to 200px width?

**Comment by Chaboi45** [comment]
Will do!

**Comment by Chaboi45** [comment]
@nwinter I just uploaded the 200px images 👍 (Incl. Tharin and the pre-existing ones)

**Comment by nwinter** [comment]
Might have missed a few in the latest; it looks like it's missing Alejandro, Amara, Anya2, Arryn, Hattori, and Okar?

**Comment by Chaboi45** [comment]
Whoops! Seems like it got cut off! I just added them now!

**Comment by nwinter** [comment]
Try running them all through ImageOptim? I got 20% file size savings [here](https://github.com/codecombat/codecombat/pull/6371/commits/cdc38db888d140efee4f03e1a6224a2c82e58182) but that branch got a bit weird with some rebasing that happened.

**Comment by Chaboi45** [comment]
Sure I'll run them again

**Comment by Chaboi45** [comment]
I ran them through imageOptim and saved about 20% average 👍

**Review by nwinter — APPROVED** [review]

**Pull request merged**
