### PR TITLE
Update nb.coffee

### PR DESCRIPTION
**Pull request by AnitaOlsen**
Please add me.

### CODE REVIEW

**Comment by Bryukh** [comment]
Thanks. Why have you left lines 418-424 commented?

**Comment by AnitaOlsen** [comment]
You are welcome. I will not translate the comments in the future. May I be added to the diplomat list, please?

**Comment by Bryukh** [comment]
Commented lines are non-translated phrases. So if you leave them commented they don't "work".

**Comment by nwinter** [comment]
Thanks @AnitaOlsen!

**Pull request merged**
