### PR TITLE
Update de-AT.coffee

### PR DESCRIPTION
**Pull request by Nitamud**
Added some translations :)

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hi, @Nitamud! Thanks for your translations! Could you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request? Also, could you correct line 502?

**Comment by Imperadeiro98** [comment]
I already told to fix line 502.

**Comment by popey456963** [comment]
I really am going blind.

**Comment by Imperadeiro98** [comment]
Don't be so mean with you, this kind of things happen.

**Comment by nwinter** [comment]
We could merge without this fix; the weird comment will get wiped in the next i18n propagation anyway.

**Comment by Imperadeiro98** [comment]
Ok!

**Comment by nwinter** [comment]
Hi @Nitamud – can we get you to [sign the CLA](http://codecombat.com/cla) real quick? Thanks!

**Comment by Imperadeiro98** [comment]
Will reopen if [CLA](https://codecombat.com/cla) gets signed.

**Pull request closed without merging**
