### PR TITLE
Updated Teacher.jade

### PR DESCRIPTION
**Pull request by popey456963**
Removed one Hour of Code reference, and expanded IE9 for clarity

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
@popey456963, what about line 29? Also, could you update the en.coffee file with your changes?

**Comment by popey456963** [comment]
Line 29 is being updated in a future push, just collecting data on everything that CodeCombat offers.  Currently updating en.coffee, never done it before though.

**Comment by popey456963** [comment]
Okay, what do I do to en.coffee?  I can't find any reference to the teachers page.

**Comment by Imperadeiro98** [comment]
Edit his section with your changes https://github.com/codecombat/codecombat/blob/master/app/locale/en.coffee#L536.

**Comment by popey456963** [comment]
Okay, just having some problems with local copy not being updated - currently installing again :)

**Pull request closed without merging**
