### PR TITLE
add dynamic scrolling to help pane (attempt #3)

### PR DESCRIPTION
**Pull request by cauerego**
This time I've tested it and made it as good as I could on my dev env, given all the issues there are with the style on the level player, both when resizing the window or when the window is too big or too small. :octopus: 

PS: Was there any other better way to make this pull request, such as editing the previous ones?

### CODE REVIEW

**Comment by nwinter** [comment]
It definitely works better to have the scrolling in the first configuration I tried, but the second one used up too much space for the spell palette and not enough for the code editor:

Before:

screenshot 2015-01-15 11 08 49

After:

screenshot 2015-01-15 11 09 00

I think the `flex-direction: row` style is messing it up. I guess that's in there so we don't have to do the extra column assignment logic, but it's making it significantly less space-efficient for variable-height "rows" of items with different amounts of properties. Thoughts?

**Comment by cauerego** [comment]
All I can say is you certainly proved me wrong there, this is way much more complicated than I'd have hoped. Probably the whole page style doesn't help, but it is complex nonetheless.

Your screen must be little less than twice the size I got here on my mbp 13'' non-retina, in which I saw no such issues. I would expect the height could be bad in some sizes, since it's dynamic based on the background height and I got no clue how that was being calculated - it just looked like it was good in my screen tests - and that's actually what probably is messing up the spell palette height.

As for the sub optimized spell palette entries, that's certainlly something to do with `flex-direction: row;` but that's also what actually makes it scrollable (if you try on smaller resolutions you'll see).

I'll test bigger sizes now and redo. It's always a bad idea to hope any version will be final, huh? :P

So, I believe I should close this and make a new PR, right?

**Comment by nwinter** [comment]
Sorry, this is some hairy CSS indeed! The thing to test would be to have a ton of items which have different numbers of properties per item. Later glasses and spellbooks often have a bunch, so are good to test with.

**Comment by nwinter** [comment]
This is related to #1777.

**Pull request closed without merging**
