### PR TITLE
Update pl.coffee

### PR DESCRIPTION
**Pull request by Adamo2499**
Translating rest of play section

### CODE REVIEW

**Comment by Bryukh** [comment]
@Adamo2499 Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Bryukh** [comment]
@Adamo2499 Could you sign our [CLA](https://contributors.codecombat.com/cla) so we can accept your PR?

**Comment by Adamo2499** [comment]
Yes, I did it

**Comment by Bryukh** [comment]
Thanks!

**Pull request merged**
