### PR TITLE
Update zh-HANT.coffee

### PR DESCRIPTION
**Pull request by ArthurLu**

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
Hello, @ArthurLu! Awesome job! Is your goal 100%?

**Comment by ArthurLu** [comment]
@Imperadeiro98 ,yes I am!

**Comment by Imperadeiro98** [comment]
Nice! Thanks to you, people that speak Traditional Chinese will be able to play in their mother language.

**Comment by ArthurLu** [comment]
That's why I do this.

**Pull request merged**
