### PR TITLE
Mongolian language translations in mon.cofee

### PR DESCRIPTION
**Pull request by Imsokray**

### CODE REVIEW

**Review by mrfinch — COMMENTED** [review]
this only adds the Mongolian translation file. I see you are adding Mongolian translations too, can you un-comment translated ones so that they can take effect?

**Comment by Imsokray** [comment]
Did as you said. Thanks, @mrfinch!

**Comment by mrfinch** [comment]
The build is failing because of your change. Can you help fix it @Imsokray? Let me know if you need help.

Error:
```
Module build failed: Error: /home/travis/build/codecombat/codecombat/app/locale/mon.coffee:460:105: error: unexpected newline
    personal_sub: # Accounts Subscription View below   "Ð¥ÑƒÐ²Ð¸Ð¹Ð½ Ð·Ð°Ñ…Ð¸Ð°Ð»Ð³Ð°" # Ð”Ð°Ð½ÑÐ½Ñ‹ Ð·Ð°Ñ…Ð¸Ð°Ð»Ð³Ñ‹Ð½ Ð´Ð¾Ð¾Ñ€ Ò¯Ð·Ð½Ñ Ò¯Ò¯
                                                                                                        ^
    L459:     personal_sub: # Accounts Subscription View below   "Ð¥ÑƒÐ²Ð¸Ð¹Ð½ Ð·Ð°Ñ…Ð¸Ð°Ð»Ð³Ð°" # Ð”Ð°Ð½ÑÐ½Ñ‹ Ð·Ð°Ñ…Ð¸Ð°Ð»Ð³Ñ‹Ð½ Ð´Ð¾Ð¾Ñ€ Ò¯Ð·Ð½Ñ Ò¯Ò¯
   ```

**Comment by Imsokray** [comment]
Just submitted a commit where I added a line. I'm afraid I'm not sure what's causing it if it's still failing. I could use your help in this case. Thanks in advance and sorry for the inconvenience.

**Review by mrfinch — APPROVED** [review]
change looks good and build passed too, thanks @Imsokray

**Pull request merged**
