### PR TITLE
Yuqiang/i18n for ai hack stack

### PR DESCRIPTION
**Pull request by smallst**
add aiscenario entry in i18n (do we want to?)
image

add ai-chat-message link in scenario i18n.
image

the edit link point to ai-chat-message i18n
image

for now i don't find a way to link ai-document , so maybe just add document entry in /1i8n too?

### CODE REVIEW

**Comment by jkcorrea** [comment]
@smallst  I'm trying to move the generation of AI HackStack schemas to the codecombat/ai repo so that it becomes the source of truth for it's own schemas. The latest changes in your PR here: https://github.com/codecombat/ai/pull/146 should have the proper schema to generate what we need. Would you mind running `npm run build:schemas` from the latest on your branch there and double checking if it matches what we need?

Definitely let me know if it's not lining up - I can help if so

**Review by nwinter — APPROVED** [review]

**Comment by smallst** [comment]
@jkcorrea hey, seems like the build:schemas works almost fine. while. i found some small issues.
1. not important but seems like gened schemas always has extra `,` at the end? (although eslint can auto remove them)
2. seems the `required` array includes more keys in gened schemas, like in ai_chat_messages, i see `documents` in the required array, while, i don't think every message would have the document, so it won't be required right ?

others LGTM.

**Comment by jkcorrea** [comment]
> 1. not important but seems like gened schemas always has extra `,` at the end? (although eslint can auto remove them)
Easily configurable in the prettier config of the `generate-schemas.ts` script, already made the change if you want to re-run it:
https://github.com/codecombat/ai/commit/7519dd04250581ad743e88b636fe8418d18d8e6d

> 2. seems the `required` array includes more keys in gened schemas, like in ai_chat_messages, i see `documents` in the required array, while, i don't think every message would have the document, so it won't be required right ?

I think that's intentional for `documents` to be required. IMO, `[]` and `null` mean different things and I'd rather have the field be defined lest we want to check for null whenever using a chat message object. If requiring the field to always be set is a pain in other parts of the codebase it's easy enough to make it optional:

```diff
// src/schemas/ai_chat_message.ts
...
-    documents: z.array(z.union([z.string(), DocumentSchema])).describe(
+    documents: z.array(z.union([z.string(), DocumentSchema])).optional().describe(
```

and then we'd want to make sure there's null guards anywhere `documents` is used, just let me know if you'd like that!

**Comment by smallst** [comment]
oh okay. if the usage of documents always start from array methods. like foreach instead of checking null first, then make it required is good to have default value as []. which make usage really simple

**Pull request merged**
