### PR TITLE
ENG-11 / ENG-164 - New Home Page

### PR DESCRIPTION
**Pull request by adamkecskes**
Route of the new home page is /home-beta for now.

This PR requires the [Storybook](https://github.com/codecombat/codecombat/pull/7237.) one.

| desktop | mobile |
| --- | --- | 
| localhost_3003_home-beta | localhost_3003_home-beta (1) |

### CODE REVIEW

**Review by mrfinch — COMMENTED** [review]
On login, instead of signup option, go to dashboard option should be there

**Review by mrfinch — COMMENTED** [review]
This PR needs to be rebased on top of current master. Some changes from package.json and/or the storybook seem to be here in this branch still

**Comment by adamkecskes** [comment]
ENG-164

**Review by mrfinch — COMMENTED** [review]
Home page looks really good and focused on AI. Thanks for your work!!!
Though the blue/purple shade gives me an impression of link.
I have added few points I noticed.

- Do we want to replace only Coco or Ozaria home page too later?
- APCSP needs to be linked based on the color used in CodeCombat Classroom. Or maybe that's intended but why not link to apcsp pages we have?
- Sign Up for beta access links for CodeCombat Jr and Hackstack Jr - Are they intended to go to current home and league page respectively?
- We have check out in `Grant and Funding Sources` section but no link there
- No link for Live Online Classes too - maybe parents page?
- No link in partner section? We have a page for it
- No link in labiray section? /libraries page?
- 'Contact Us' button at the bottom doesn't do anything
- Our help center link navigates away from CodeCombat to zendesk - how about opening that in new tab instead?
- Are we relying on existing tracking or do you plan to add tracking for CTAs in a different PR?
- Learn to Code using AI on the first section goes out of screen on iphone see view. Can you fix it? Though this is low-priority and non-blocking

**Review by mrfinch — COMMENTED** [review]
I ran lighthouse on our new home page.
Some changes from it that we should make:
1. 
Convert to webp
[testimonal/sandra.jpg](http://localhost:3000/images/pages/home-v3/testimonal/sandra.jpg)

2.
Large GIFs are inefficient for delivering animated content. Consider using MPEG4/WebM videos for animations and PNG/WebP for static images instead of GIF to save network bytes. [Learn more about efficient video formats]
(https://developer.chrome.com/docs/lighthouse/performance/efficient-animated-content/?utm_source=lighthouse&utm_medium=devtools)
[solutions/box_4.gif](http://localhost:3000/images/pages/home-v3/solutions/box_4.gif)

We do similar optimization on ozaria home page:
```
video(autoplay loop muted playsinline)
            source(src="/images/ozaria/home/gifs/track_progress.webm" type="video/webm")
            source(src="/images/ozaria/home/gifs/track_progress.mp4" type="video/mp4")
```

3. 
Lot of images do not have an alt attribute

4.
 ```<frame> or <iframe>``` elements do not have a title
Screen reader users rely on frame titles to describe the contents of frames. [Learn more about frame titles](https://dequeuniversity.com/rules/axe/4.8/frame-title)

5.
Links are not crawlable - a.CTA.contact-modal
Search engines may use href attributes on links to crawl websites. Ensure that the href attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered. [Learn how to make links crawlable](https://support.google.com/webmasters/answer/9112205)

**Pull request merged**
