### PR TITLE
Change visible references of 'HipChat' to 'Slack'.

### PR DESCRIPTION
**Pull request by dillonforrest**
Addresses #3144.

Simple find-and-replace. I know these types of commits are tedious to code review, so in the interest of saving your eyes, here are the changes I made:

1. In `app/templates`, I replaced "HipChat channel" (case sensitive) with "Slack channel"
2. In `app/templates`, I replaced remaining instances of "HipChat" (case sensitive) with "Slack"
3. In `app/templates`, I replaced all hipchat urls with slack urls.
4. In `app/locale`, I replaced "HipChat" (case sensitive) with "Slack".

Here are some things I did NOT change in this PR:
- The logo remains unchanged -- it's still a hipchat logo
- Method names with "HipChat" are unchanged
- Coffee object keys containing "hipchat" (case insensitive) are unchanged

I'm happy to add or remove changes as you see fit!

### CODE REVIEW

**Comment by dillonforrest** [comment]
Oh wow, my CI build is dreadful! D: Will investigate later after I get some sleep!

**Comment by basicer** [comment]
@dillonforrest Not your fault, those tests fail randomly.  It's a known issue.

**Comment by nwinter** [comment]
Looks good except let's not change multicore and server/ since we actually haven't set up Slack API integration and can keep the HipChat one for our internal use for now until we decide to fully switch over if we find Slack truly better. Can you update the PR? Thanks!

**Comment by dillonforrest** [comment]
@basicer Okay, thanks for letting me know!

@nwinter Cool, thanks for the feedback! I just updated the PR. Happy to make other changes as well!

**Comment by nwinter** [comment]
Thanks @dillonforrest!

**Pull request merged**
