### PR TITLE
Clean i18n when forking an object

### PR DESCRIPTION
**Pull request by nixel2007**
If i got it right, this should fix this issue https://github.com/codecombat/codecombat/issues/2500

### CODE REVIEW

**Comment by nwinter** [comment]
I think we also need to unset `i18nCoverage`, since that's what triggers the query for Diplomats to translate it.

**Comment by nixel2007** [comment]
i checked the model and can't find i18nCoverage for thangType. is i18nCoverage available at ForkModal?

**Comment by nwinter** [comment]
It's available for all models with i18n via [the translation coverage plugin properties](https://github.com/codecombat/codecombat/blob/master/app/schemas/models/thang_type.coffee#L187-L187).

**Comment by nixel2007** [comment]
Oh, thank you, I see.
Added new unset.

**Comment by nwinter** [comment]
Great!

**Pull request merged**
