### PR TITLE
Added ability to delete account

### PR DESCRIPTION
**Pull request by laituan245**
(Issue #1825)

Now you can delete your own account.

screenshot from 2015-02-20 07 34 02

### CODE REVIEW

**Comment by nwinter** [comment]
Wow, this is really great! I asked @sderickson and he suggested that instead of just deleting the User object, we should remove all the properties except for _id, and maybe also add a `deleted: true` property, so that we can return HTTP 410 Gone codes when a user is deleted. Care to update this to include that?

**Comment by laituan245** [comment]
I have updated the code. Instead of deleting the User object, now I only remove all the properties except for _id. I don't add a `deleted: true` property, because probably `anonymous: true` property can also be an indication of a deleted account.  

However, I don't understand what you want to see with the "HTTP 410" thing. So for example, if you go to the page http://codecombat.com/user/thisaccountdoesnotexist, an error page should be displayed ?

**Comment by nwinter** [comment]
I don't think we need to implement the 410 now if we don't want, but I think the intent is to modify the `getById` database handler to return a HTTP 410 "Gone" error code instead of an HTTP 404 "Not found" error code [here](https://github.com/codecombat/codecombat/blob/master/server/commons/Handler.coffee#L214-L214) if we know that this is a deleted record. In that sense it might be easier to add a `deleted` property, because then it doesn't need custom logic specific to the User schema to determine what might mean that the model has been deleted, and we can use it for other models as well if we want a placeholder to indicate that there was once a model there.

**Comment by laituan245** [comment]
@nwinter I have added a `deleted: true` property to a deleted account. I also have modified some parts like the way you said. Thanks for your comments.

**Comment by nwinter** [comment]
Excellent work! Thanks @laituan245!

**Pull request merged**
