### PR TITLE
Vi translation

### PR DESCRIPTION
**Pull request by duybkict**

### CODE REVIEW

**Comment by Imperadeiro98** [comment]
@nwinter

**Comment by duybkict** [comment]
sc2
Here is the minor layout bug on /community page, I fixed it along with the previous commit

**Comment by Imperadeiro98** [comment]
@nwinter

**Comment by duybkict** [comment]
I separated the bug fix into another pull request #3651

**Comment by Imperadeiro98** [comment]
Thank you. Sorry for not merging right away, but I didn't want to make changes to other parts of the code that I was not sure of.

**Comment by duybkict** [comment]
No prob, I get why you have to do that :)

**Pull request merged**
