### PR TITLE
line 41 translated

### PR DESCRIPTION
**Pull request by leshark**
Instead of this:
#    forgot_learning: "I think they actually forgot that they were actually learning something." 
line 42
 forgot_learning: "Я думаю они действительно забудут, что они изучают что-то."

### CODE REVIEW

**Comment by leshark** [comment]
it is just a beginning of big translation!

**Comment by leshark** [comment]
I got this error : The command "./node_modules/karma/bin/karma start --browsers Firefox --single-run --reporters dots"

**Comment by Imperadeiro98** [comment]
Hello, @leshark! Thank you for contributing. Can you sign our [CLA](https://codecombat.com/cla) so that I can merge your pull request?

The error you are getting is not related to your changes.
Btw, can you remove the English version of the string you translated from the ru.coffee file?

**Comment by Imperadeiro98** [comment]
Close in favor of #3752

**Pull request closed without merging**
