### PR TITLE
Only lock spacebar and default code when the player is lower level (issue 2406)

### PR DESCRIPTION
**Pull request by h3yduck**
For issue #2406

### CODE REVIEW

**Comment by nwinter** [comment]
Thinking about this some more, I just realized that we should put these required levels into the Level itself, so that the code can't get out of sync with the data. What if we added an option to have a number instead of a boolean for `disableSpaces` and `lockDefaultCode`, and then we could fill these expected levels in the Campaign Editor instead of just using `true` and then overriding it later?

We could edit [this schema](https://github.com/codecombat/codecombat/blob/master/app/schemas/models/level.coffee#L310-L310):

```
disableSpaces: { type: ['boolean', 'integer'] }
```

... and then update the SpellView code to also be able to handle the `me.level()` comparison if it's a number instead of just `true`. What do you think?

**Comment by h3yduck** [comment]
Sounds great! I'm on it!

**Comment by h3yduck** [comment]
For some reason i couldn't change the disableSpaces/lockDefaultCode attributes in the editor from true/false to numbers. I'm not familiar with the editor, so it migth be my fault.

**Comment by nwinter** [comment]
You updated the schema and it still wouldn't let you change it? Can you post a screenshot of that not working in the CampaignEditor?

**Comment by h3yduck** [comment]
image

Of course! When i click on disableSpaces value it switches between true-false. I tried to change it by navigating with keyboard also, but its true-false only.

**Comment by nwinter** [comment]
Ohhh, I see. We also need to update the schema here, too:

https://github.com/codecombat/codecombat/blob/master/app/schemas/models/campaign.schema.coffee#L64-L64

(Because the CampaignEditor denormalizes it, the same property is in two places.)

**Comment by h3yduck** [comment]
Ah thanks! It works now!

**Pull request merged**
