### PR TITLE
Basic translations for nl-NL.coffee

### PR DESCRIPTION
**Pull request by SebastiaanBekker**

### CODE REVIEW

**Comment by SebastiaanBekker** [comment]
@Bryukh just signed it.

**Comment by Bryukh** [comment]
Thanks! Merged.

**Comment by SebastiaanBekker** [comment]
hi @Bryukh can i also translate dynamic content from github? or do i need your tooling? (sorry, but is less intuitive for me)

**Comment by nwinter** [comment]
No, dynamic content needs to be translated via https://direct.codecombat.com/i18n – more here: https://github.com/codecombat/codecombat/wiki/Diplomat-Home

**Pull request merged**
